README.md
codes/requirements.txt

It's best to create a pip requirements file, using pip -r requirements.txt, this will need the user to `cd` into the codes directory, or provide a direct path to the requirements.txt.
The optimizations to the README.md are to remove unnecessary characters from the URL's and to update the installation instructions to follow the requirements.txt usage.

pip requirements file, and optimisations to readme

---

codes/data/REDS_dataset.py

As written in #76, there is a key mismatching bug with LQ frames. This happen when `border_mode=False`.
I think this is a major issue and please review this or check #76 ASAP.

fix key mismatching with LQ frames

---

codes/train.py

When `use_tb_logger` is False, `tb_logger.close` occurs `UnboundLocalError: local variable 'tb_logger' referenced before assignment`
So `tb_logger.close` should be called when `use_tb_logger` is True

close tb_logger after training when use_tb_logger is True

---

mmedit/apis/train.py

IterBasedRunner: `cfg` only has `total_iters`.

fix _non_dist_train

---

mmedit/datasets/pipelines/normalization.py

Fix Normalize redundant loop bug

---

setup.py

Try to fix #123
`setup.py` has a mistake during getting the version of the package.

Fix setup.py get_hash bug

---

mmedit/apis/train.py
mmedit/datasets/builder.py

In order to increase the speed, add PoolDataLoader for parrots.

add PoolDataLoader for parrots

---

docs/conf.py
docs/index.rst
docs/stat.py

add_modelzoo_statistics

---

mmedit/models/backbones/encoder_decoders/decoders/plain_decoder.py

Temporarily 
fix #175
fix #168

Use nn.MaxUnpool2d

---

tools/data/matting/comp1k/check_extended_fg.py

Prints the difference of `abs((fg - extended_fg) * alpha)`

Check extended fg

---

mmedit/datasets/pipelines/augmentation.py
mmedit/datasets/pipelines/crop.py

Use np.random instead of random

---

mmedit/apis/train.py
tools/test.py

Refactor loader_cfg of main() in tools/test.py.
There is a bug in the master branch:
`TypeError: type object got multiple values for keyword argument 'samples_per_gpu'`.
That is because `loader_cfg` contains two `'samples_per_gpu'`:
1. `samples_per_gpu=1,`
2. ` **cfg.data.get('test_dataloader', {}),`, while `cfg.data['test_dataloader']=dict(samples_per_gpu=1),`
The second one has been replaced by `loader_cfg.update(cfg.data.get('test_dataloader', {}))`.

Refactor loader_cfg.

---

mmedit/datasets/pipelines/__init__.py
mmedit/datasets/pipelines/down_sampling.py
tests/test_down_sampling.py

Add down_sampling.py for generating LQ image from GT image, which is required in [Learning Continuous Image Representation with Local Implicit Image Function](https://arxiv.org/pdf/2012.09161.pdf)

Add down_sampling.py for generating LQ image from GT image.

---

mmedit/datasets/__init__.py
mmedit/datasets/sr_folder_dataset_gt.py
mmedit/datasets/sr_folder_gt_dataset.py
tests/test_datasets.py

Add `SRFolderDatasetGT`, only read GT image from folder.
And LQ image will be generated by `DownSampling` (in another PR).

Add SRFolderDatasetGT.

---

configs/restorers/liif/README.md
configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py
configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py
configs/restorers/liif/liif_edsr_norm_x2~4_c64b16_g1_1000k_div2k.py

Liif config

---

mmedit/models/backbones/encoder_decoders/decoders/plain_decoder.py

Hi
This PR fix ONNX conversion of maxunpool2d by adding offset to indices.

fix onnx conversion of maxunpool2d

---

mmedit/core/evaluation/metrics.py
tests/test_metrics.py

Many existing SR methods compute PSNR and SSIM on Y-channel. However, MMEditing currently does not support this operation. This PR adds this operation by adding an argument `color_space` in `psnr` and `ssim`.

Support Y-channel PSNR and SSIM

---

mmedit/datasets/pipelines/__init__.py
mmedit/datasets/pipelines/augmentation.py
tests/test_augmentation.py

BasicVSR and IconVSR extend the 7-frame Vimeo-90K sequences to 14 frames by mirroring them. This PR adds support to this operation by adding `MirrorExtend`.

Add MirrorExtend for training BasicVSR and IconVSR

---

configs/restorers/basicvsr/basicvsr_reds4.py
configs/restorers/basicvsr/basicvsr_vimeo90k_bd.py
configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py
mmedit/datasets/pipelines/__init__.py
mmedit/datasets/pipelines/augmentation.py
tests/test_augmentation.py

Add `GenerateFrameIndicesForRecurrent` for randomly picking segments from a video sequence. This is used for training recurrent networks.

Add 'GenerateFrameIndicesForRecurrent'

---

docs/faq.md
mmedit/apis/test.py
tools/test.py

In the current test program (`mmedit/apis/test.py`), the GPU memory occupied by the processed data is not released in time, and `CUDA out of memory ` if the test data is large.
Fix the issue in this PR.

Tiny fix of `mmedit/apis/test.py`

---

docs/tools_scripts.md
setup.cfg
tools/pytorch2onnx.py

Hi,
This PR adds restorer model support to pytorch2onnx.
Dynamic shape, dynamic batch and visualize support are also added too.

[Feature] Update pytorch2onnx

---

docs/tools_scripts.md
mmedit/core/export/__init__.py
mmedit/core/export/wrappers.py
requirements/tests.txt
setup.cfg
tests/test_onnx_wraper.py
tools/deploy_test.py

This PR includes:
<table>
<tr>
<th>Model</th>
<th>Config</th>
<th>Dataset</th>
<th>Metric</th>
<th>PyTorch</th>
<th>ONNX Runtime</th>
</tr>
<tr>
<td rowspan="6">ESRGAN</td>
<td rowspan="6">esrgan_x4c64b23g32_g1_400k_div2k.py</td>
<td rowspan="2">Set5</td>
<td>PSNR</td>
<td>28.2700</td>
<td>28.2619</td>
</tr>
<tr>
<td>SSIM</td>
<td>0.7778</td>
<td>0.7784</td>
</tr>
<tr>
<td rowspan="2">Set14</td>
<td>PSNR</td>
<td>24.6328</td>
<td>24.6290</td>
</tr>
<tr>
<td>SSIM</td>
<td>0.6491</td>
<td>0.6494</td>
</tr>
<tr>
<td rowspan="2">DIV2K</td>
<td>PSNR</td>
<td>26.6531</td>
<td>26.6532</td>
</tr>
<tr>
<td>SSIM</td>
<td>0.7340</td>
<td>0.7340</td>
</tr>
<tr>
<td rowspan="6">ESRGAN</td>
<td rowspan="6">esrgan_psnr_x4c64b23g32_g1_1000k_div2k.py</td>
<td rowspan="2">Set5</td>
<td>PSNR</td> …

[Feature]: Add onnx evaluation tool

---

tools/publish_model.py

According to the [official PyTorch docs](https://pytorch.org/docs/stable/generated/torch.save.html)
```
The 1.6 release of PyTorch switched torch.save to use a new zipfile-based file format. torch.load still retains the 
ability to load files in the old format. If for any reason you want torch.save to use the old format, pass the kwarg 
_use_new_zipfile_serialization=False.
```
As a result, when using PyTorch version>=1.6 to publish models, errors occur when loading weights from URL. This PR fixes this error by adding `_use_new_zipfile_serialization=False` for `torch.__version__ >= '1.6'`

Fix error in publish_model.py for pt>=1.6

---

mmedit/core/evaluation/metrics.py
tests/test_metrics.py

Fix PSNR when input is uint8

---

tools/get_flops.py

As discussed in #306,  Existing `get_flops.py` does not accept video inputs with size `(t, c, h, w)`. Therefore, the function is not compatible with video SR models such as EDVR, BasicVSR.
This PR adds the support of FLOPs computation of video SR models, by accepting `--shape t c h w`. For example, for BasicVSR, we can compute the FLOPs by using the following command.
```python tools/get_flops.py configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py --shape 5 3 180 320```

[Feature] Support FLOPs calculation of video SR models

---

mmedit/models/backbones/sr_backbones/ttsr_net.py
tests/test_ttsr.py

Backbone of Texture Transformer Network for Image Super-Resolution.

[Feature] Add Structural Feature Encoder

---

mmedit/models/backbones/sr_backbones/ttsr_net.py
tests/test_ttsr.py

Part of Texture Transformer Network for Image Super-Resolution.

[Feature] Add Cross-Scale Feature Integration

---

mmedit/datasets/__init__.py
mmedit/datasets/sr_folder_ref_dataset.py
tests/test_datasets.py

add sr_folder_ref_dataset

---

demo/restoration_demo.py

There are currently two restoration demos. `restoration_demo.py` is for image restoration, and `restoration_video_demo.py` is for video restoration. These two may be confusing. 
In this PR `restoration_demo.py` raises an error if `img_path` does not end with `.png` or `.jpg`. In the error message, we suggest the use of `restoration_video_demo.py` for video restoration.

Add error message in restoration_demo.py

---

configs/restorers/basicvsr/basicvsr_reds4.py
configs/restorers/basicvsr/basicvsr_vimeo90k_bd.py
configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py
configs/restorers/iconvsr/iconvsr_reds4.py
configs/restorers/iconvsr/iconvsr_vimeo90k_bd.py
configs/restorers/iconvsr/iconvsr_vimeo90k_bi.py
mmedit/models/restorers/basicvsr.py

As discussed in #273, training of BasicVSR halted due to the settings of `find_unused_parameters`. This PR fixes the error in PyTorch1.8 by removing the modification of  `find_unused_parameters` during training. `find_unused_parameters` is kept `True` throughout training.

Fix `find_unused_parameters` in PyTorch 1.8 for BasicVSR

---

demo/restoration_demo.py
demo/restoration_video_demo.py
mmedit/apis/restoration_video_inference.py
mmedit/datasets/pipelines/augmentation.py

As mentioned in issue #323, there will be errors if the file names are not formated as `{v:08d}.png`. This may cause problems if one use custom filename format.
In this PR, we modify `GenerateSegmentIndices` so that one can use different filename formats. But note that the frame indices must start from 0.

[Feature] Support different filename templates in GenerateSegmentIndices

---

docs/getting_started.md

Corrected path in restoration config path for demo

Minor correction in getting_started.md

---

demo/restoration_video_demo.py
mmedit/apis/restoration_video_inference.py
mmedit/datasets/pipelines/augmentation.py

As mentioned in #335, the existing video_restoration_demo does not support sequences whose start frame index is not 0. This may cause problems in custom video sequences.
This PR changes the behavior of the function `GenerateSegmentIndices` so that the image names can now start from number other than 0. Changes are:
1. Instead of assuming the start frame index is 0, we add the value `start_idx` to the extracted indices.
2. `video_restoration_demo` and `video_restoration_inference` are modified. 
**Note**: The image names must be consecutive. That means, a sequence with images `0000.png, 0004.png, 0020.png` is not supported.

Support start_index in GenerateSegmentIndices

---

mmedit/datasets/sr_vid4_dataset.py
tests/test_datasets.py

When computing quantitative metrics (e.g. PSNR) for video SR, we usually compute the PSNR for each folder first, and then compute the average of the averages". In the existing `SRVid4Dataset`, only the average of all frames is supported. 
This PR adds support of computing the average of averages by adding an argument `metric_average_mode`.

[Feature] Support 'folder' mode for computing average metric for video SR models

---

mmedit/models/extractors/__init__.py
mmedit/models/extractors/feedback_hour_glass.py
tests/test_extractors.py

Part of DIC
HourGlass --> FeedbackHourGlass --> DIC

[Feature] Add HourGlass

---

tools/data/super-resolution/vimeo90k/README.md
tools/data/super-resolution/vimeo90k/preprocess_vimeo90k_dataset.py

Added folder structure, and instructions to use `prepare_vimeo90k_dataset.py`

[Doc] Update description for Vimeo90K

---

mmedit/models/backbones/sr_backbones/dic_net.py
tests/test_dic_net.py

[Feature] Add FeedbackBlock

---

mmedit/models/backbones/sr_backbones/dic_net.py
tests/test_dic_net.py

[Feature] Add FeedbackBlockHeatmapAttention

---

mmedit/models/extractors/__init__.py
mmedit/models/extractors/feedback_hour_glass.py
tests/test_extractors.py

[Feature] Add merge_heatmap_to_5

---

mmedit/__init__.py

As discussed in #376, `_load_checkpoint_with_prefix` is used in StyleGAN, but is not included in `mmcv < 1.3`. 
This PR changes the minimum mmcv version specified in `mmedit/__init__.py`, from `1.0.2` to `1.3`.

Change mmcv minimum version

---

mmedit/apis/restoration_video_inference.py
tests/test_inference.py

In [restoration_video_inference.py](https://github.com/ckkelvinchan/mmediting/blob/704eb2c614fb0bce40eab6a028be41bc93df7032/mmedit/apis/restoration_video_inference.py#L78), when using 
```
for i in range(0, data.size(1) - window_size):
```
a part of the input frames is omitted. This results in fewer output frames.
This PR fixes the bug and replace the original command by 
```
for i in range(0, data.size(1) - 2 * (window_size // 2)):
```

[Fix] Fix bug in restoration_video_inference.py

---

tools/data/super-resolution/vid4/README.md

There are multiple issues with the download link of Vid4 dataset for video super-resolution.
This PR adds the document for Vid4 dataset. The dataset link is included (my Google Drive link).

[Docs] Add documents and download link for Vid4

---

mmedit/core/mask.py

In recent PRs, the unittests show an error on `brush_stroke_mask`.
This PR fixes the error, by changing `np.asarray(mask, dtype=getattr(np, dtype))` to `np.array(mask).astype(dtype=getattr(np, dtype))`

[Fix] Fix [brush_stroke_mask] error in unittest

---

configs/restorers/basicvsr/basicvsr_reds4.py
configs/restorers/basicvsr/basicvsr_vimeo90k_bd.py
configs/restorers/basicvsr/basicvsr_vimeo90k_bi.py
configs/restorers/edvr/edvrm_wotsa_x4_g8_600k_reds.py
configs/restorers/edvr/edvrm_x4_g8_600k_reds.py
configs/restorers/iconvsr/iconvsr_reds4.py
configs/restorers/iconvsr/iconvsr_vimeo90k_bd.py
configs/restorers/iconvsr/iconvsr_vimeo90k_bi.py
configs/restorers/tdan/tdan_vimeo90k_bdx4_ft_lr5e-5_800k.py
configs/restorers/tdan/tdan_vimeo90k_bdx4_lr1e-4_400k.py
configs/restorers/tdan/tdan_vimeo90k_bix4_ft_lr5e-5_400k.py
configs/restorers/tdan/tdan_vimeo90k_bix4_lr1e-4_400k.py
configs/restorers/tof/tof_x4_vimeo90k_official.py
demo/restoration_video_demo.py
mmedit/apis/restoration_video_inference.py
mmedit/core/mask.py
tests/test_inference.py

Most of the video SR models in MMEditing take inputs with range [0, 1], but TDAN takes inputs with range [-0.5, 0.5]. Therefore, `Normalize` should be added to the pipeline in `restoration_video_inference.py`.
`demo_pipeline` is added in the configuration files of each VSR model. The demo will look for `demo_pipeline`.
An additional modification is that the output images are named according to `args.filename_tmpl` and `args.start_idx`.

[Fix] Fix normalization in restoration_video_inference

---

mmedit/datasets/builder.py

Support persistent worker for PyTorch >= 1.7

[Feature] Support persistent worker

---

mmedit/datasets/sr_folder_multiple_gt_dataset.py
mmedit/datasets/sr_folder_video_dataset.py
mmedit/datasets/sr_vimeo90k_multiple_gt_dataset.py
tests/test_data/test_datasets/test_sr_dataset.py

As raised in #395, some datasets use `glob` or `scandir` when loading annotations. These functions are not compatible with ceph. As a result, it is unable to train some models when ceph is used.
1. For `SRFolderMultipleGTDataset` and `SRFolderVideoDataset`, an argument `ann_file` is added. If it is provided, annotations will be loaded from the file.
2. For `SRVimeo90KMultipleGTDataset`, `glob` is removed, and the file paths are replaced by the standard Vimeo-90K file names.

[Feature] Support loading annotation from file for video SR datasets

---

docs/demo.md

I thought that there is a mistake in docs/demo.md, in the Restoration (Image) part. The config file 'configs/restorer/esrgan/esrgan_x4c64b23g32_1x16_400k_div2k.py'  is pointing to the err one, it should be  'configs/restorer/esrgan/esrgan_x4c64b23g32_g1_400k_div2k.py', right?

Fix  typo in docs/demo.md, in Restoration (Image) part，cause config file  not found.

---

mmedit/apis/test.py

Fix multi-node distributed test

---

mmedit/apis/train.py

when use EvalIterHook  in _non_dist_train in .mmedit/apis/train.py, it will raise keyError since the key 'data_time' is not exsist
set the priority of EvalIterHook lower then IterTimerHook

priority of EvalIterHook shold be lower then IterTimerHook

---

mmedit/apis/train.py

[Fix] Change priority of DistEvalIterHook to 'LOW'

---

tools/test.py

When using `test.py` without computing any metrics, `KeyError: 'eval_result'` is reported as `test.py` assumes that evaluation has been done. 
This PR adds a condition in `test.py`. With this modification, `dataset.evaluate` is bypassed if `eval_result` is not contained in `outputs`.

[Enhance] Disable `dataset.evaluate` when `eval_result` is not in outputs

---

mmedit/core/hooks/__init__.py
mmedit/core/hooks/ema.py
tests/test_runtime/test_ema_hook.py

Many existing methods, such as Real-ESRGAN, use exponential moving average hook during training.
This PR supports exponential moving average hook. Users can define this hook in the configuration file.
Codes adopted from MMGeneration.

[Feature] Exponential Moving Average Hook

---

mmedit/models/restorers/__init__.py
mmedit/models/restorers/real_esrgan.py
tests/test_models/test_restorers/test_real_esrgan.py

This PR supports the model for Real-ESRNet and Real-ESRGAN.

[Feature] Real-ESRGAN model

---

docs/quick_run.md
docs_zh-CN/quick_run.md

Fix typo and translate quick_run.md to Chinese

[Doc] Chinese translation of quick_run.md 

---

configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py
configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py
tests/test_data/test_pipelines/test_random_degradations.py

As stated in #616, when using `RandomResize`, an error is raised when list is used for `target_size`.
This PR fixes the problem by changing `target_size` from list to tuple in the configuration files.

[Fix] Change target_size for RandomResize from list to tuple

---

mmedit/datasets/pipelines/matlab_like_resize.py

The current version has a typo in `_cubic`. This affects the resizing result
This PR fixes the typo, and the resulting resizing operation is similar to MATLAB's `imresize`.

[Fix] Fix bug in MATLABLikeResize

---

mmedit/core/evaluation/metrics.py
tests/test_metrics/test_metrics.py

Existing NIQE in MMEditing has a difference to the MATLAB results (https://github.com/roimehrez/PIRM2018) due to the following two reasons
1. cv2 downsampling is used instead of MATLAB downsampling
2. rounding operation is omitted.
This PR improves NIQE by 
1. using `MATLABLikeResize` for downsampling,
2. adding a rounding operation

[Enhance] Align NIQE to MATLAB results

---

.github/workflows/build.yml
.github/workflows/lint.yml

Skip CI when some specific files were changed to save the CI resources.
Reference: https://github.com/open-mmlab/mmcv/pull/1533
1. Update .github/workflows/build.yml
2. Add .github/workflows/lint.yml

[Enhance] Skip CI when some specific files were changed

---

docs/conf.py
requirements/docs.txt
setup.cfg

Fix the error when building HTML (https://readthedocs.org/projects/mmcv/builds/15458392/)
Reference: https://github.com/open-mmlab/mmcv/pull/1560
- docs/conf.py
- setup.cfg
- requirements/docs.txt

[Fix] Remove outdated code in docs/conf.py

---

.github/workflows/build.yml
mmedit/datasets/pipelines/__init__.py
mmedit/datasets/pipelines/random_degradations.py
tests/test_data/test_pipelines/test_random_degradations.py

To support random video compression during training, for RealBasicVSR.
1. Modify random_degradaions.py to support video compression
2. Modify build.yml to install `av` in CI

[Feature] Support random video compression during training

---

mmedit/datasets/pipelines/loading.py
tests/test_data/test_pipelines/test_loading.py

As suggested by #642, support conversion to y-channel images, since some models are trained on y-channels.
Modify **mmedit/datasets/pipelines/loading.py** by adding the argument `convert_to` in the corresponding functions.

[Feature] Support conversion to y-channel when loading images

---

README.md
README_zh-CN.md

The contribtion.md link has already been moved from mmdet to mmcv.
Moreover, translation to "guideline" is improved.

Update link to contribution in README.md

---

mmedit/models/common/flow_warp.py

As reported in #638, the comment of `flow_warp` has a problem. This PR fixes the comment by changing `(w, h, 2)` to `(h, w, 2)`.
Modify `mmedit/models/common/flow_warp.py`.

[Fix] Fix flow_warp comment

---

docs/demo.md

\configs\restorers\glean\glean_in128out1024_2x4_300k_ffhq_celebahq.py" does not exist
When I change the commmand to /configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py it can work

Update GLEAN config path in demo.md

---

docs/getting_started.md

The  “configs\restorers\esrgan\esrgan_x4c64b23g32_1x16_400k_div2k.py" does not exist
But when I change the command to esrgan_x4c64b23g32_g1_400k_div2k.py it can work.

Update ESRGAN config path in getting_started.md

---

.github/workflows/build.yml
mmedit/__init__.py
mmedit/models/registry.py
requirements/runtime.txt

MMEditing did not use mmcv's MODELS registry as root/parent registry. This PR makes it impossible to build models across projects.
mmpose/models/registry.py
```Python
from mmcv.cnn import MODELS as MMCV_MODELS
from mmcv.utils import Registry
MODELS = Registry('model', parent=MMCV_MODELS)
BACKBONES = MODELS
COMPONENTS = MODELS
LOSSES = MODELS
MODELS = Registry(
'models', build_func=build_model_from_cfg, parent=MMCV_MODELS)
```

[Enhance]: Use mmcv root model registry.

---

docs/conf.py

In #644, Model Zoo and Datasets disappeared in readthedocs. This PR adds them back.
Modify **conf.py**

[Doc] Fix the error of Model Zoo and Datasets in docs

---

mmedit/datasets/pipelines/random_degradations.py
tests/test_data/test_pipelines/test_random_degradations.py

Support Stochastic degradations for RealBasicVSR. The random degradations are slightly different for each image in a video sequence. The extent of differences is determined by the step_size.
Modify test_random_degradations.py

[Features] Support stochastic degradations for RealBasicVSR

---

.dev_scripts/github/update_model_index.py
configs/inpainting/deepfillv1/metafile.yml
configs/inpainting/deepfillv2/metafile.yml
configs/inpainting/global_local/metafile.yml
configs/inpainting/partial_conv/metafile.yml
configs/mattors/dim/metafile.yml
configs/mattors/gca/metafile.yml
configs/mattors/indexnet/metafile.yml
configs/restorers/basicvsr/metafile.yml
configs/restorers/basicvsr_plusplus/metafile.yml
configs/restorers/dic/metafile.yml
configs/restorers/edsr/metafile.yml
configs/restorers/edvr/metafile.yml
configs/restorers/esrgan/metafile.yml
configs/restorers/glean/metafile.yml
configs/restorers/iconvsr/metafile.yml
configs/restorers/liif/metafile.yml
configs/restorers/rdn/metafile.yml
configs/restorers/real_esrgan/metafile.yml
configs/restorers/srcnn/metafile.yml
configs/restorers/srresnet_srgan/metafile.yml
configs/restorers/tdan/metafile.yml
configs/restorers/tof/metafile.yml
configs/restorers/ttsr/metafile.yml
configs/synthesizers/cyclegan/metafile.yml
configs/synthesizers/pix2pix/metafile.yml

Capitalize the first letter of the task name in the metafile.
Will be auto-completed by script.

[Docs] Capitalize the first letter of the task name in the metafile.

---

mmedit/datasets/pipelines/crop.py
tests/test_data/test_pipelines/test_crop.py

FixedCrop will support `list` type

[Feature] Update FixedCrop for list

---

tools/data/super-resolution/reds/README.md
tools/data/super-resolution/reds/README_zh-CN.md
tools/data/super-resolution/reds/crop_sub_images.py

Add a script to crop REDS images into sub-images, for faster IO. Similar to the operation for [DIV2K](https://github.com/open-mmlab/mmediting/blob/master/tools/data/super-resolution/div2k/preprocess_div2k_dataset.py).
1. Add **tools/data/super-resolution/reds/crop_sub_images.py**
2.  Modify README

[Feature] Add script to crop REDS images into sub-images for faster IO

---

requirements/runtime.txt

The latest `opencv-python` causes error in CI. This PR limits the version of it.
Modify requirements/runtime.txt

Limit opencv-python version

---

.github/workflows/build.yml

In order to solve: https://github.com/open-mmlab/mmediting/runs/4697550155?check_suite_focus=true#step:12:109
In the previous GitHub workflow, installation of Pillow==6.2.2 is useless because it will be overwritten afterward in `pip install -r requirements.txt`. The actual version installed finally is 8.4.0. This version is compatible with old torchvision because `PILLOW_VERSION` is re-imported (which is removed in version 7), so previous CI works until 2022-Jan-02 when Pillow 9 was released. So I tried to use Pillow<9 to keep this compatibility with old-versioned torchvision as well as other dependencies.

[CI] Update Pillow from 6.2.2 to 8.4 in CI

---

configs/restorers/basicvsr_plusplus/basicvsr_plusplus_c64n7_8x1_600k_reds4.py
mmedit/datasets/sr_reds_multiple_gt_dataset.py
tests/test_data/test_datasets/test_sr_dataset.py

As indicated in #671, training BasicVSR++ with 8 GPUs causes an error, since REDS4 contains 4 validation folders, which cannot be tested with 8 GPUs. This PR fixes the issue by repeating the validation data (e.g. from 4 folders to 8)
1. Modify mmedit/datasets/sr_reds_multiple_gt_dataset.py
2. Modify config of BasicVSR++

[Feature] Add argument 'repeat' to SRREDSMultipleGTDataset

---

mmedit/apis/train.py

Reference: https://github.com/open-mmlab/mmdetection/pull/7016

[Feature] Support CPU training

---

.github/workflows/build.yml
requirements/runtime.txt

**Note**: `coverage run --branch --source mmedit -m pytest tests` should be a single line command. When combined with multiple commands in a single step, failure of pytest will not cause CI to fail!

Add CI for windows

---

.gitignore
docs/en/conf.py
docs/en/index.rst
docs/en/merge_docs.sh
docs/en/stat.py

The current doc build system modifies md files in place, which makes local development hard and faulty. This PR explicitly creates temporary files for intermediate md files. 
Preview: https://mmediting--769.org.readthedocs.build/en/769/
A side effect is that autogenerated links will have "_tmp" in their paths.

[Docs] Update doc build system

---

demo/video_interpolation_demo.py
mmedit/apis/video_interpolation_inference.py
mmedit/models/video_interpolators/basic_interpolator.py
tests/test_inference.py

**motivation**
Video interpolation demo read the whole video into RAM, which can easily lead to overflow.

[Feature] Support streaming reading of frames in video interpolation demo

---

mmedit/apis/restoration_video_inference.py

Instead of loading all LQ images to GPU, which causes CUDA OOM, we first put them in CPU, and then extract to GPU when we use them.
- Modify `mmedit/apis/restoration_video_inference.py`

[Enhance] Put LQ into CPU for restoration_video_demo

---

tools/data/super-resolution/div2k/preprocess_div2k_dataset.py

when I run follow code to prepare my customed dataset.
```
python custom/tools/data/super-resolution/div2k/preprocess_div2k_dataset.py \
--data-root data/91-images \
--scales 2 3 4 \
--crop-size 33 \
--step 14
```
a error occured as follows:
> mkdir data/91-images/DIV2K_train_HR_sub ...
> [                                                  ] 0/91, elapsed: 0s, ETA:All processes done.
> Traceback (most recent call last):
>   File "custom/tools/data/super-resolution/div2k/preprocess_div2k_dataset.py", line 390, in <module>
>     main_extract_subimages(args)
>   File "custom/tools/data/super-resolution/div2k/preprocess_div2k_dataset.py", line 69, in main_extract_subimages
>     opt['step'] = args.step // scale
> TypeError: unsupported operand type(s) for //: 'str' and 'int'
I think step, …

[Fix] Update preprocess_div2k_dataset.py

---

configs/restorers/edsr/README.md

The EDSR is evaluated in **RGB** channels, but `README` in EN says ''Evaluated on Y channels''.

[Docs] Fix Y/GRB mistake in EDSR README

---

mmedit/datasets/pipelines/augmentation.py
tests/test_data/test_pipelines/test_augmentation.py

original: `flip_ratio=1.` means always no flip and `flip_ratio=0.` means always flip
after:      `flip_ratio=1.` means always flip and `flip_ratio=0.` means always no flip

[Fix] `flip_ratio` in `RandomAffine` pipeline is inverted

---

demo/generation_demo.py
demo/inpainting_demo.py
demo/matting_demo.py
demo/restoration_demo.py
demo/restoration_face_demo.py
demo/restoration_video_demo.py
demo/video_interpolation_demo.py
docs/en/demo.md
docs/en/getting_started.md
docs/zh_cn/demo.md
docs/zh_cn/getting_started.md
mmedit/utils/__init__.py
mmedit/utils/cli.py
tests/test_utils/test_modify_args.py
tools/data/matting/comp1k/README.md
tools/data/matting/comp1k/README_zh-CN.md
tools/data/matting/comp1k/preprocess_comp1k_dataset.py
tools/data/super-resolution/vimeo90k/README.md
tools/data/super-resolution/vimeo90k/README_zh-CN.md
tools/data/super-resolution/vimeo90k/preprocess_vimeo90k_dataset.py
tools/evaluate_comp1k.py

closes https://github.com/open-mmlab/mmediting/issues/804

[Fix] use hyphen for command line args in demo & tools 

---

docs/en/getting_started.md
docs/en/quick_run.md
docs/zh_cn/getting_started.md
docs/zh_cn/quick_run.md
tools/test.py
tools/train.py

https://github.com/open-mmlab/mmdetection/blob/3e2693151add9b5d6db99b944da020cba837266b/tools/train.py#L72
Sometimes we want to use a custom runtime configuration for a given configuration file.
This feature is already supported in other mm-frameworks, so I added it.

[Improve] Add `--cfg-options` in train/test scripts

---

mmedit/datasets/comp1k_dataset.py
mmedit/datasets/pipelines/__init__.py
mmedit/datasets/sr_annotation_dataset.py
mmedit/datasets/sr_facial_landmark_dataset.py
mmedit/datasets/sr_folder_dataset.py
mmedit/datasets/sr_folder_gt_dataset.py
mmedit/datasets/sr_folder_multiple_gt_dataset.py
mmedit/datasets/sr_folder_ref_dataset.py
mmedit/datasets/sr_folder_video_dataset.py
mmedit/datasets/sr_lmdb_dataset.py
mmedit/datasets/sr_reds_dataset.py
mmedit/datasets/sr_reds_multiple_gt_dataset.py
mmedit/datasets/sr_vid4_dataset.py
mmedit/datasets/sr_vimeo90k_dataset.py
mmedit/datasets/sr_vimeo90k_multiple_gt_dataset.py
mmedit/datasets/vfi_vimeo90k_dataset.py
mmedit/models/backbones/sr_backbones/basicvsr_net.py
mmedit/models/backbones/sr_backbones/basicvsr_pp.py
mmedit/models/backbones/sr_backbones/iconvsr.py

1. Correct "annoations" to "annotations".
2. Correct "propgation" to "propagation".
3. Remove undefined functions in `mmedit/datasets/pipelines/__init__.py`.
Some sequences may start from a frame index other than 0.
If without annotation files, `SRFolderVideoDataset` cannot process these sequences correctly; sequences must start from 0.
But in many cases, we use our own data-sets to train video SR methods such as EDVR, and the sequences in these data-sets may start from a frame index other than 0.

[Enhance] Support non-zero frame index for `SRFolderVideoDataset` & Fix Typos

---

mmedit/models/common/flow_warp.py

This version of flow_warp is faster than original one and the consistency of results between two implementations has been checked.

[Enhance] Optimize IO for `flow_warp`

---

.github/workflows/build.yml
requirements/runtime.txt

Try fix #830
Wait until next release of opencv-python

[Improve] Skip problematic opencv-python versions

---

.dev_scripts/README.md
.dev_scripts/doc_link_checker.py

update dev_scripts for link checking
update dev_scripts for link checking
**Before PR**:
**After PR**:

[Enhance] update dev_scripts for link checking

---

.dev_scripts/create_ceph_configs.py
mmedit/utils/io_utils.py
tests/test_utils/test_io_utils.py

This PR fixes the following bugs:
1.  Use `mmengine.mkdir_or_exist` instead `mmcv` ones.
2. Fix the Ceph dataset path mapping in `create_ceph_config.py`.
3. Avoid uploading visualization results to Ceph due to not all users have the same bucket (i.e., `s3://work_dirs`) on Ceph. (Uploading strategy in `create_ceph_config.py` will be revised later.)
If so, …

[Fix] Fix some known bugs.

---

.dev_scripts/download_models.py
.dev_scripts/test_benchmark.py
.dev_scripts/train_benchmark.py
tools/test.py

Include mmgen's url in benchmark. Also fix test.py.
**Before PR**:
**After PR**:

[Fix] Benchmark related bugs

---

mmedit/apis/restoration_video_inference.py

Fix restoration_video_demo bug of some input directory cases.
mmedit/apis/restoration_video_inference.py
**Before PR**:
**After PR**:

[Fix] fix restoration_video_demo bug

---

mmedit/models/backbones/sr_backbones/rdn.py

When using the RDB, I found this bug.
The RDB adopts residual learning between `x` and `self.lff(self.layers(x))`. However, the channel number of `x` is `in_channels `, while the output channels of `self.lff` is `channel_growth`.
This bug did not cause error in the past because the default `channel_growth` of the RDN class is 64, which is not indicated in any config files of RDN. At the same time, all config files use `mid_channels=64`, which is equal to the `channel_growth`.
However, when someone uses the RDB class independently, this bug may cause error.
Issue: https://github.com/open-mmlab/mmediting/issues/1136
I change the number of output channels of LFF from `channel_growth` to `in_channels`.
@plyfager
**Before PR**:
**After PR**:

[Bug Fixed] Correct the number of output channels of LFF in RDB

---

tests/test_models/test_editors/test_stylegan3/test_stylegan3_utils.py

As issue #1301.
Add unit test with boundary conditions
**Before PR**:
**After PR**:

[Enhancement] Reduce the randomness in unit test of `stylegan3_utils.py`

---

tools/model_converters/pytorch2onnx.py

basicvsr models fail to run pytorch2onnx.py
Add `num_frames` parameters
python tools/model_converters/pytorch2onnx.py configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py  realbasicvsr_wogan_c64b20_2x30x8_lr1e-4_300k_reds_20211027-0e2ff207.pth …

[Fix] fix vsr models pytorch2onnx

---

mmedit/models/backbones/sr_backbones/rdn.py

Currently, MMEditing supports RDN following https://github.com/yjn870/RDN-pytorch/blob/master/models.py#L21 , whose implementation is slightly different from the official implementation: https://github.com/sanghyun-son/EDSR-PyTorch
Code has been fixed in https://github.com/open-mmlab/mmediting/pull/1292 and https://github.com/open-mmlab/mmediting/pull/1311
In this pull request, we add the official implementation in the docstring. 
Does the modification introduce changes that break the backward-compatibility of the downstream …

[Doc] update docstring of RDN

---

configs/ttsr/ttsr-gan_x4c64b16_1xb9-500k_CUFED.py

The discriminator's learning rate of TTSR model is misaligned with 1.x and 0.x (1e-4 and 1e-5 respectively).
Change lr to `1e-5`.
**Before PR**:
**After PR**:

[Config] Revise discriminator's learning rate of TTSR to align with 0.x version

---

configs/singan/singan_fish.py
demo/singan_demo.py
mmedit/datasets/__init__.py
mmedit/datasets/singan_dataset.py
mmedit/datasets/transforms/formatting.py
mmedit/models/editors/mspie/pe_singan_generator.py
mmedit/models/editors/singan/singan.py
tests/test_datasets/test_singan_dataset.py
tests/test_datasets/test_transforms/test_formatting.py
tests/test_models/test_editors/test_mspie/test_pe_singan_generator.py
tests/test_models/test_editors/test_singan/test_singan.py

1. PESinGAN with inter-pad have bugs
2. SinGAN dataset is missing
3. SinGAN demo is missing
1. Add `pack_all` field in `PackEditInputs`
2. Add `SinGANDataset`
3. Fix forward logic of `SinGANMSGeneratorPE` when `input_sample` is `None`
4. Fix ema related logic of `SinGAN`
5. Add `singan_demo.py`
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep …

[Enhancement] Fix PESinGAN-inter-pad setting + add SinGAN Dataset + add SinGAN demo

---

mmedit/apis/restoration_video_inference.py
mmedit/apis/video_interpolation_inference.py

`LoadImageFromFile` is supposed to be in the types of exceptions when reading videos, as `LoadImageFromFileList` is no longer required.
minor change.
**Before PR**: …

[Fix] fix types of exceptions in demos

---

.dev_scripts/README.md
.dev_scripts/train_benchmark.py

Support deterministic training in training benchmark. Please refers to [readme](https://github.com/LeoXing1996/mmediting/blob/5610fdcbbe66f56741e48572a3049f7ac5080d10/.dev_scripts/README.md).
Support `--deterministic` flag in `train_benchmark.py`. If `--deterministic` is set, `randomness` fields in config will be modified by `--cfg-options=randomness.determinstic=True`. Environment variable `CUBLAS_WORKSPACE_CONFIG=:4096:8` will be added to the job script as well. 
Does the modification introduce changes that break the …

[Enhancement] Support deterministic training in benchmark

---

mmedit/models/data_preprocessors/gen_preprocessor.py

MMEngine adds type checking in [`BaseDataPreprocessor.cast_data`](https://github.com/open-mmlab/mmengine/pull/602) and `TypeError` will be raised when `int` or `float` is passed. 
Avoid passing `float` and `int` to `BaseDataPreprocessor.cast_data`.
If this PR introduces a new …

[Fix] Avoid cast int and float in GenDataPreprocessor

---

docs/en/advanced_guides/3_transforms.md
docs/en/user_guides/1_config.md
docs/en/user_guides/4_train_test.md
tools/dataset_converters/image_translation/README.md
tools/dataset_converters/unconditional_gans/README.md

Some docs use `GenDataSample` and `PackGenInputs` as examples, which are used in MMGeneration.
Change `GenDataSample` to `EditDataSample`.
Change `PackGenInputs` to `PackEditInputs`. …

[Docs] Revise docs (change PackGenInputs and GenDataSample to mmediting ones)

---

.dev_scripts/train_benchmark.py
configs/esrgan/esrgan_psnr-x4c64b23g32_1xb16-1000k_div2k.py
configs/esrgan/esrgan_x4c64b23g32_1xb16-400k_div2k.py
mmedit/models/editors/esrgan/rrdb_net.py

ESRGAN cannot load the pretrained model correctly.
1. Adopt pretrained model loading logic with `BaseModule`
2. Revise test and val setting as master branch.
**Before …

[Fix] Revise config and pretrain model loading in esrgan

---

mmedit/datasets/transforms/crop.py
mmedit/utils/__init__.py
mmedit/utils/setup_env.py
tests/test_utils/test_setup_env.py

In `crop.py`, mmdet, which is a optional installed package, is imported at the start of the file. This is very unfriendly for users.
Support `try_import` and use `try_import` to import `mmdet`.
If this PR introduces a new feature, it is better to list some use cases here, and …

[Enhancement] Support `try_import` for `mmdet`

---

mmedit/models/base_models/base_conditional_gan.py
mmedit/models/editors/stylegan2/stylegan2_discriminator.py
mmedit/models/editors/stylegan2/stylegan2_generator.py
mmedit/models/editors/stylegan2/stylegan2_modules.py
mmedit/models/editors/stylegan3/stylegan3_modules.py
tests/test_models/test_editors/test_stylegan2/test_stylegan2_discriminator.py
tests/test_models/test_editors/test_stylegan2/test_stylegan2_generator.py
tests/test_models/test_editors/test_stylegan2/test_stylegan2_modules.py
tests/test_models/test_editors/test_stylegan3/test_stylegan3_modules.py

1. EG3D use camera poses as conditional input in a slightly modified StyleGANv2 discriminator. This algorithm adds a mapping network before Discriminator as embedding layer.
2. StyleGAN's official repo support conditional input in discriminator.
1. Add `MappingNetwork` in `StyleGAN2Discriminator`
2. Support no noise input (`x is None`) in `MappingNetwork`
3. Support conditional input in `StyleGAN2Generator`
4. Support no noise injection in `ModulatedStyleConv`
5. Support `skip` input + w/o upsample in `ModulatedToRGB`
6. Support update latent mean (`w_avg`) by EMA
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to …

[Enhancement] Support conditional input for StyleGAN modules

---

.dev_scripts/update_model_index.py

In mmediting master branch "update_model_index.py" locates in ".dev_scripts/github" while in dev-1.x and 1.x branch it locates in ".dev_scripts" . Before python 3.9 "\_\_file\_\_" uses a relative path and pre-commit  runs well. In python 3.9 "\_\_file\_\_" uses an absolute path resulting in pre-commit error. 
Correct the path to enable pre-commit runs well in python 3.9
The ones who use python3.9
**Before PR**:
**After PR**:

[Fix] Wrong path resulsting in pre-commit error in Python 3.9

---

configs/restorers/real_esrgan/realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost.py

fix realesrnet test dataset
fix realesrnet test dataset
**Before PR**:
**After PR**:

[Fix] fix realesrnet test dataset

---

mmedit/models/editors/eg3d/renderer.py
tests/test_models/test_editors/test_eg3d/test_camera.py
tests/test_models/test_editors/test_eg3d/test_renderer.py

Torch < 1.8.0 does not implement `torch.nan_to_num`.
Support nan_to_num for torch < 1.8.0 in EG3D's renderer and add mock in torch version for `test_camera` and `test_renderer` to cover more lines.
If this PR introduces a new feature, it is better to list some use cases here, …

[Enhanchment] Fix unit test of EG3D Render for torch < 1.8.0

---

tests/test_evaluation/test_metrics/test_ppl.py

PPL initializes an LPIPS model to extract image features, which takes too much time. Therefore we mock the LPIPS model.
Time-consuming reduce from the 20s to 10s.
Mock LPIPS in PPL metric.
If this PR introduces a new feature, it is better to list some use cases here, and …

[Enhancement] Mock LPIPS module in PPL metric

---

.dev_scripts/README.md

Fix the incorrect command in `.dev_scripts/README.md`
Fix the incorrect command in `.dev_scripts/README.md`
**Before PR**:
**After PR**:

[Fix] fix documentation link checker

---

mmedit/models/editors/disco_diffusion/guider.py
tests/test_apis/test_inferencers/test_text2image_inferencers.py
tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion.py

`guider.py` relay `torchvision.transforms > 0.7.0`.
Skip unit test when `torchvision.__version__` is less than or equal to 0.7.0.
**Before PR**:
**After PR**:

[Enhancement] Fix text2image inferencer + disco diffusion GPU test

---

.dev_scripts/update_model_index.py
configs/disco_diffusion/README.md
configs/disco_diffusion/metafile.yml
configs/ggan/metafile.yml
configs/pggan/metafile.yml
configs/pix2pix/metafile.yml
configs/sagan/metafile.yml
configs/singan/metafile.yml
configs/sngan_proj/metafile.yml
configs/styleganv1/metafile.yml
configs/styleganv3/metafile.yml
configs/wgan-gp/metafile.yml

1. fix the link of config in disco-diffusion readme. 
1. update `update_model_index.py` to update metafile correctly. 
2. update the link of config in disco-diffusion readme.  …

fix config path in disco-diffusion

---

mmedit/models/editors/ddpm/ddpm_scheduler.py

Docstring and type hint miss in initialization function of DDPM scheduler
as title

[Docs] Add docstring and type hint for initialization function of DDPM Scheduler

---

mmedit/datasets/transforms/aug_pixel.py

First PR. Just a mini doc fix as a try LOL.
Change argname in docstring to match the actual arguments.
**Before PR**:
**After PR**:

[Docs] fix docstring

---

tools/train.py

Dump config into `work_dir`.
```
cfg.dump(osp.join(cfg.work_dir, osp.basename(args.config)))
```

dump config

---

configs/_base_/datasets/decompression_test_config.py
configs/glean/glean_in128out1024_4xb2-300k_ffhq-celeba-hq.py
configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py
configs/real_esrgan/realesrnet_c64b23g32_4xb12-lr2e-4-1000k_df2k-ost.py
configs/swinir/swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-grayCAR10.py
mmedit/datasets/transforms/aug_pixel.py
mmedit/datasets/transforms/random_degradations.py
mmedit/models/editors/real_esrgan/real_esrgan.py

Refactor random degradation to compute on the range of 0-255
**Before PR**:
**After PR**:

[Refactor] Refactor random degradation

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml
setup.py

As title. The modification refers to #1589.
Remove Python3.6 from `setup.py` and unit tests. 
**Before PR**:
**After PR**:

[Fix] Fix CircleCI's OpenCV installation error on master branch.

---

tests/test_metrics/test_inceptions.py
tests/test_models/test_restorers/test_basic_restorer.py

`torch <= 1.5.1` do not support interpolation on `torch.uint8`. Therefore we skip unit tests related to inception network when `torch <= 1.5.1`.
As title.
**Before …

[Fix] skip unit test related to inception when torch <= 1.5.1

---

tests/test_models/test_restorers/test_basic_restorer.py

`torch <= 1.5.1` do not support interpolation on `torch.uint8`. Therefore we skip unit tests related to inception network when `torch <= 1.5.1`.
As title.
**Before …

[Fix] skip restorer's unit test when torch <= 1.5.1

---

.circleci/test.yml
mmedit/models/editors/ddpm/denoising_unet.py
tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py

[Fix] fix sd torch16 ut

---

tools/model_converters/pytorch2onnx.py

Fix the error `RuntimeError: "upsample_bicubic2d" not implemented for 'Byte'`
**Before PR**:
**After …

[Fix] fix dtype of pytorch2onnx

---

docs/en/.dev_scripts/update_model_zoo.py

fix bug during updating model zoo when building docs
**Before PR**:
**After PR**:

[Fix] fix bug during updating model zoo when building docs

---

docs/en/get_started/quick_run.md

```
❯ PYTHONPATH='.'$PYTHONPATH python quick_run.py
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/lqy/Desktop/mmediting/quick_run.py:3 in <module>                                           │
│                                                                                                  │
│    1 import mmcv                                                                                 │
│    2 from mmedit.apis import init_model, restoration_inference                                   │
│ ❱  3 from mmedit.engine.misc import tensor2img                                                   │
│    4                                                                                             │
│    5 config = …
```

[Fix] fix import error in quick run demo doc

---

configs/_base_/datasets/cifar10_noaug.py
configs/disco_diffusion/README.md
configs/disco_diffusion/tutorials.ipynb
configs/stable_diffusion/README.md
demo/gradio-demo.py
mmedit/__init__.py
mmedit/apis/inferencers/inference_functions.py
mmedit/edit.py
mmedit/registry.py
projects/glide/configs/README.md
requirements/mminstall.txt
tools/analysis_tools/get_flops.py
tools/model_converters/pytorch2onnx.py
tools/test.py
tools/train.py

[Feature] Support auto import modules from registry

---

tools/dataset_converters/df2k_ost/preprocess_df2k_ost_dataset.py
tools/dataset_converters/div2k/preprocess_div2k_dataset.py
tools/dataset_converters/reds/crop_sub_images.py

There are several scripts under tools/dataset_converters accpet int arguments, e.g., '--n-thread'. However, some of those arguments are not declared as int explicitly,  they will be regarded as str if we pass those arguments to the scripts by ourselves, and therefore generate an error message in the following steps.
Define the int arguments with type=int explicitly in those buggy scripts under tools/dataset_converters. …

[Fix] fix dataset_converters scripts int arg passing bug

---

mmedit/models/common/downsample.py

These are changes to support pixel unshuffling for inputs of various sizes during onnx export. The warning is as follows:
```
/opt/conda/lib/python3.8/site-packages/mmedit/models/common/downsample.py:14: TracerWarning: Converting a tensor to a Python boolean might cause the trace to be incorrect. We can't record the data flow of Python values, so this value will be treated as a constant in the future. This means that the trace might not generalize to other inputs!
if h % scale != 0 or w % scale != 0: …
```

[Fix] dynamic exportable pixel unshuffle

---

mmedit/apis/inferencers/unconditional_inferencer.py
mmedit/edit.py

[Enhancement] support all unconditional models inference.

---

mmedit/models/base_models/base_conditional_gan.py
mmedit/models/base_models/base_edit_model.py
mmedit/models/base_models/base_gan.py
mmedit/models/base_models/one_stage.py
mmedit/models/data_preprocessors/edit_data_preprocessor.py
mmedit/models/editors/basicvsr/basicvsr.py
mmedit/models/editors/eg3d/eg3d.py
mmedit/models/editors/liif/liif.py
mmedit/models/editors/pggan/pggan.py
mmedit/models/editors/singan/singan.py
mmedit/structures/edit_data_sample.py
tests/test_apis/test_inferencers/test_eg3d_inferencer.py
tests/test_models/test_data_preprocessors/test_edit_data_preprocessor.py
tests/test_models/test_data_preprocessors/test_mattor_preprocessor.py
tests/test_models/test_editors/test_eg3d/test_eg3d.py
tests/test_structures/test_edit_data_sample.py

The `forward` function for GAN models is unclear. Therefore we modify them in this PR.
Revise the forward logic for GAN models.
**Before PR**:
**After PR**:

[Enhancement] Make forward logic more clear for GAN models

---

mmedit/models/data_preprocessors/edit_data_preprocessor.py

Pytorch 1.6 do not support int32 as index in `index_select`. This PR adopts index to `int64` (`LongTensor`) to pass the unit test.
As title.
**Before PR**:
**After …

[Fix] Use LongTensor in index_select for pt16

---

mmedit/core/hooks/visualization.py
tools/train.py

Save visual images according to the order in the config.
Currently the images are concatenated according to the order in the results dict, and the order is not configurable:
<https://github.com/open-mmlab/mmediting/blob/d18fc44868082b3bff4d80973b09b1f2f2db88a3/mmedit/core/hooks/visualization.py#L75>
I changed this line to 
```
img_list = [results[k] for k in self.res_name_list if k in results]
```
so that we can configure the order of images being saved using  `visual_config.res_name_list`.

Make the image order in VisualizationHook as it is in the config

---

mmedit/utils/sampler.py
tests/test_utils/test_sampler.py

The original count logic of samplers are wrong and causes one more loop in visualization.
Revise the counting logic.
**Before PR**:
**After PR**:

Corrected iterator counting logic of sampler

---

tools/train.py

[Fix] Fix  accepting an unexpected argument `local-rank`  in PyTorch 2.0

---

mmedit/structures/edit_data_sample.py
tests/test_structures/test_edit_data_sample.py

Text-to-image tasks need text prompts, which are `str` type, as input. Therefore we support an additional attribute called `prompt` for `EditDataSample`.
Add `prompt` attribute for `EditDataSample`.
If this PR introduces a new feature, it is better to list some use cases …

[Enhancement] Support string type (prompt) in EditDataSample

---

mmedit/models/editors/tof/tof_vfi_net.py

Similar to PR #1710: Fix warp typo in TOFlow.
I simply change the `wrap_frame` to `warp_frame`. The renamed variables are all local and thus the modification would not influences other functions.
**Before PR**:
**After PR**:

[Fix] Fix warp typo

---

configs/stable_diffusion/stable-diffusion_ddim_denoisingunet.py
mmedit/models/data_preprocessors/edit_data_preprocessor.py
mmedit/models/diffusion_schedulers/__init__.py
mmedit/models/diffusion_schedulers/ddim_scheduler.py
mmedit/models/editors/ddpm/denoising_unet.py
mmedit/models/editors/guided_diffusion/adm.py
mmedit/models/editors/stable_diffusion/__init__.py
mmedit/models/editors/stable_diffusion/stable_diffusion.py
mmedit/models/editors/stable_diffusion/vae.py
mmedit/models/utils/__init__.py
mmedit/models/utils/model_utils.py
tests/test_models/test_base_archs/test_wrapper.py
tests/test_models/test_diffusion_schedulers/test_init.py
tests/test_models/test_editors/test_ddpm/test_denoising_unet.py
tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
tests/test_models/test_utils/test_model_utils.py
tools/train.py

Support more flexible initialization for `StableDiffusion`.
1. Revise the initialization function for `StableDiffusion`
2. Revise the output type of `StableDiffusion.infer`
3. Add some necessary attribute and method for `DenoisingUnet` and `DDIMScheduler`.
4. Register MMEdit's `AutoencoderKL` as `EditAutoencoderKL` to support build from config.
5. Support a wrapper for diffusers scheduler to support load from pretrained.
6. Revise some docstring and remove some useless comments.
Does the modification introduce changes that break …

[Enhancement] Revise StableDiffusion and corresponding components

---

configs/controlnet/README.md
configs/controlnet/controlnet-1xb1-fill50k.py
configs/controlnet/controlnet-canny.py
configs/controlnet/controlnet-pose.py
configs/controlnet/controlnet-seg.py
configs/controlnet/metafile.yml
mmedit/models/editors/__init__.py
mmedit/models/editors/controlnet/__init__.py
mmedit/models/editors/controlnet/controlnet.py
mmedit/models/editors/controlnet/controlnet_utils.py
model-index.yml
tests/test_models/test_editors/test_controlnet/test_controlnet.py
tests/test_models/test_editors/test_controlnet/test_controlnet_utils.py

As title.
As title.
Running the following codes, you can get a text-generated image.
```python
import mmcv
from mmengine import Config
from PIL import Image
from mmedit.registry import MODELS
from mmedit.utils import register_all_modules
register_all_modules()
cfg = Config.fromfile('configs/controlnet/controlnet_canny.py')
controlnet = MODELS.build(cfg.model).cuda()
prompt = 'Room with blue walls and a yellow ceiling.'
control_url = 'https://user-images.githubusercontent.com/28132635/230288866-99603172-04cb-47b3-8adb-d1aa532d1d2c …
```

[Feature] Support ControlNet

---

mmedit/engine/runner/edit_loops.py
mmedit/engine/runner/loop_utils.py
mmedit/evaluation/evaluator.py
tests/test_engine/test_runner/test_loop_utils.py
tests/test_evaluation/test_evaluator.py

Sometimes, we want to run **validation loop** for visualization and do not run an evaluation. Therefore we revise `EditEvaluator` to support **"non-metric"**.
As title …

[Enhancement] Support evaluator without metric

---

mmedit/models/base_archs/__init__.py
mmedit/models/base_archs/lora.py
tests/test_models/test_base_archs/test_lora.py

As title.
As title.
```python
Use case:
>>> 1. set all lora with same parameters
>>> lora_config = dict(
>>>     rank=4,
>>>     scale=1,
>>>     target_modules=['to_q', 'to_k', 'to_v'])
>>> 2. set lora with different parameters
>>> lora_config = dict(
>>>     rank=4,
>>>     scale=1,
>>>     target_modules=[
>>>         # set `to_q` the default parameters
>>>         'to_q',
>>>         # set `to_k` the defined parameters
>>>         dict(target_module='to_k', rank=8, scale=1),
>>>         # set `to_v` the defined `rank` and …
```

[Enhancement] Support LoRA for linear modules

---

mmagic/apis/inferencers/inpainting_inferencer.py
mmagic/apis/mmagic_inferencer.py

[Enhancement] support all inpainting models inferencer

---

.circleci/config.yml
mmagic/models/archs/__init__.py
mmagic/models/archs/tokenizer.py
mmagic/models/editors/disco_diffusion/clip_wrapper.py
tests/test_models/test_archs/test_tokenizer.py
tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion_clip_wrapper.py
tests/test_models/test_editors/test_stable_diffusion/test_clip_wrapper.py

Textual inversion need add external embeddings to the original embedding layer. Therefore we support a tokenizer wrapper and  a module named `EmbeddingLayerWithFixes` to support this feature.
As title.
```python
>>> 1. Add token to tokenizer and get the token id.
>>> …
```

[Feature] Support tokenizer wrapper and support EmbeddingLayerWithFixes

---

demo/README.md
mmagic/apis/inferencers/__init__.py
mmagic/apis/mmagic_inferencer.py
requirements/runtime.txt

[Enhance] support image restoration inferencer

---

docs/zh_cn/migration/amp.md
docs/zh_cn/migration/distributed_train.md
docs/zh_cn/migration/optimizers.md
docs/zh_cn/migration/visualization.md

Translate documents amp, distributed_train, optimizers and visualization into Chinese
To provide Chinese version of documents
The empty documents in `docs/zh_cn/migration` amp.md, distributed_train.md, optimizers.md and visualization .md were added with corresponding Chinese translation.
No!
No new features added in this PR.
**Before PR**:
**After PR**:

Translate documents amp, distributed_train, optimizers and visualization into Chinese

---

mmagic/models/editors/dreambooth/dreambooth.py
mmagic/models/editors/stable_diffusion/stable_diffusion.py

Fix #1867
As title.
**Before PR**:
**After PR**:

[Fix] Fix dtype error in StableDiffusion and DreamBooth training

---

mmagic/models/editors/controlnet/controlnet.py
mmagic/models/editors/dreambooth/dreambooth.py
mmagic/models/editors/stable_diffusion/stable_diffusion.py

Support noise offset introduced by https://www.crosslabs.org/blog/diffusion-with-offset-noise, which enables stable diffusion to generate lighter or darker images.
As title. …

[Enhancement] Support noise offset in stable diffusion training

---

tools/gui/component.py

[Fix] fix gui VideoSlider bug

---

configs/controlnet/README.md
configs/controlnet/controlnet-pose.py
configs/controlnet/metafile.yml
demo/README.md
mmagic/apis/inferencers/base_mmagic_inferencer.py
mmagic/apis/inferencers/text2image_inferencer.py
mmagic/apis/mmagic_inferencer.py

[Enhance] support controlnet inferencer

---

docs/en/howto/transforms.md
docs/zh_cn/howto/transforms.md
mmagic/datasets/transforms/__init__.py
mmagic/datasets/transforms/albumentations.py
requirements/optional.txt
requirements/runtime.txt
requirements/tests.txt
tests/test_datasets/test_transforms/test_albumentations.py

[Feature] support Albumentations augmentation transformations and pipeline

---

README.md
docs/en/howto/models.md
docs/en/user_guides/config.md
docs/zh_cn/howto/models.md
mmagic/registry.py
mmagic/utils/setup_env.py
projects/flow_style_vton/inference.py

1. Fix README TOC typos.
2. Fix README GCA link.
3. Change "train.py" to "tools/train.py".
4. Change "tutorials/registry.html" to "advanced_tutorials/registry.html".
5. Change the default scope from "mmedit" to "mmagic".

[Fix] Typos and mistakes

---

mmagic/__init__.py
requirements/mminstall.txt
requirements/runtime.txt

`mmcv` and `mmengine` are repeatedly listed in "requirements/{mminstall.txt,runtime.txt}". Following [MMDetection](https://github.com/open-mmlab/mmdetection/tree/main/requirements), we removed `mmcv` and `mmengine` from "requirements/runtime.txt", and kept those in "requirements/mminstall.txt".
The reason is that we have manually installed MMCV and MMEngine before installing MMagic as indicated in the [Doc](https://github.com/open-mmlab/mmagic/blob/main/docs/en/get_started/install.md). As a result, there is no need to require `mmcv` and `mmengine` in "requirements/runtime.txt", which are to be installed with "setup.py".
After this modification, the installation of MMagic is much faster.
We added `Click` and `pandas` in "requirements/runtime.txt". They are required by …

[Fix] Requirements

---

mmagic/models/archs/attention_injection.py

```
the parameters of transformer block in newest diffusers have been changed.
previous attention injection runs with diffusers==0.14.0. 
```
If this PR introduces a new feature, it is better to list some use cases …

[Fix] fix attention injection for higher version of diffusers

---

.dev_scripts/inference_benchmark.sh
.dev_scripts/test_benchmark.yml
.dev_scripts/train_benchmark.yml

[Enhance] upodate benchmark scripts

---

docs/zh_cn/get_started/quick_run.md

DID: D_kwDOI32y584AURZn from https://aicarrier.feishu.cn/sheets/shtcnE5FlKLcg4vMjMMoq4kFL1f?sheet=db3ad0
Translate `docs/en/get_started/quick_run.md` to `docs/zh_cn/get_started/quick_run.md`
Translate `docs/en/get_started/quick_run.md` to `docs/zh_cn/get_started/quick_run.md` …

[Doc] add zh_cn quick_run

---

mmagic/apis/inferencers/controlnet_animation_inferencer.py
mmagic/models/editors/controlnet/controlnet.py
mmagic/models/editors/dreambooth/dreambooth.py
mmagic/models/editors/stable_diffusion/stable_diffusion.py

[Fix] fix sd and controlnet fp16 bugs

---

docs/en/migration/overview.md
docs/zh_cn/migration/amp.md
docs/zh_cn/migration/overview.md

Translate `migration/overview.md` into Chinese and fix some typos
1. Translate `migration/overview.md` into Chinese
2. Add missing blanks in `zh_cn/migration/amp.md`
3. Fix some typos in `en/migration/overview.md`

[Docs] Translate `migration/overview.md` into Chinese and fix some typos

---

docs/zh_cn/migration/data.md

MMSIG task
docs/zh_cn/migration/data.md
**Before PR**:
**After PR**:

[MMSIG] Translate data migration document to Chinese

---

mmagic/models/editors/controlnet/controlnet.py
tests/test_models/test_editors/test_controlnet/test_controlnet.py

Related to #1927 
If number control is 1, the control will be repeated for `num_images_per_prompt * len(prompt)` times.
Otherwise the number control must equal to number of prompt, and will be repeated for `num_images_per_prompt` times.
Unit tests are revised as well.
If this …

[Fix] Fix num_images_per_prompt in controlnet

---

docs/zh_cn/migration/schedule.md

Translate `migration/schedule.md` into Chinese
**Before PR**:
**After PR**:

[MMSIG] translate `migration/schedule.md` into chinese document

---

configs/textual_inversion/README.md
configs/textual_inversion/metafile.yml
configs/textual_inversion/textual_inversion.py
mmagic/datasets/__init__.py
mmagic/datasets/textual_inversion_dataset.py
mmagic/models/editors/__init__.py
mmagic/models/editors/dreambooth/dreambooth.py
mmagic/models/editors/textual_inversion/__init__.py
mmagic/models/editors/textual_inversion/textual_inversion.py
model-index.yml

Support textual inversion
**Before PR**:
**After PR**:

[Feature] Support Textual Inversion

---

mmagic/models/editors/lsgan/lsgan_discriminator.py
mmagic/models/editors/lsgan/lsgan_generator.py
mmagic/models/editors/mspie/mspie_stylegan2_discriminator.py
mmagic/models/editors/mspie/mspie_stylegan2_generator.py
mmagic/models/editors/mspie/mspie_stylegan2_modules.py
mmagic/models/editors/mspie/positional_encoding.py
mmagic/models/editors/pggan/pggan_discriminator.py
mmagic/models/editors/pggan/pggan_generator.py
mmagic/models/editors/pggan/pggan_modules.py
mmagic/models/editors/sagan/sagan_discriminator.py
mmagic/models/editors/sagan/sagan_generator.py
mmagic/models/editors/sagan/sagan_modules.py
mmagic/models/editors/stylegan1/stylegan1_discriminator.py
mmagic/models/editors/stylegan1/stylegan1_generator.py
mmagic/models/editors/stylegan1/stylegan1_modules.py
mmagic/models/editors/stylegan1/stylegan_utils.py
mmagic/models/editors/stylegan2/stylegan2_discriminator.py
mmagic/models/editors/stylegan2/stylegan2_generator.py
mmagic/models/editors/stylegan2/stylegan2_modules.py
mmagic/models/editors/stylegan3/stylegan3_generator.py
mmagic/models/editors/stylegan3/stylegan3_modules.py

Use mmengine.basemodole instead of nn.module

---

docs/en/advanced_guides/evaluator.md
docs/zh_cn/advanced_guides/evaluator.md

misuage of `torch.flip`
`torch.flip(input, dims) `
`dims`  is of list / tuple type, instead of a int;
We change `1` $\rightarrow$ `[1]`.

[BUG] fix a bug in mmagic/models/editors/stylegan2/stylegan2_generator.py

---

docs/zh_cn/user_guides/train_test.md

I made this PR to practice my translation skills and get familiar with the procedures of Git.
Simplified Chinese version of tutorial 4 document translated from its corresponding English version.
**Before PR**:
**After PR**:

[Doc]: Update zh_cn/user_guides/train_test.md

---

.circleci/test.yml
tests/test_models/test_archs/test_wrapper.py

In https://github.com/huggingface/diffusers/commit/029fb41695a7940c213d914471fb41a1df67aa17, `diffusers` changed the default parameter of 'safe_serialization' to True in the `ModelMixin.save_pretrained` function. This make `diffusers` use `safetensors` to save model checkpoint, which need `torch >= 2.0.1`.
Add `safe_serialization=False` in unit test.
If so, please describe how it breaks the compatibility and how the …

revise default args for unit test

---

mmagic/configs/eg3d/eg3d_cvt-official-rgb_afhq-512x512.py
mmagic/configs/eg3d/eg3d_cvt-official-rgb_ffhq-512x512.py
mmagic/configs/eg3d/eg3d_cvt-official-rgb_shapenet-128x128.py
setup.cfg

Update `setup.cfg` for new configs. Refers to [MMPretrain](https://github.com/open-mmlab/mmpretrain/blob/d2ccc44a2c8e5d49bb26187aff42f2abc90aee28/setup.cfg#L25-L33).
If this PR introduces a new feature, it is …

[Enhancement] Update flake8 checking config in setup.cfg

---

mmagic/configs/_base_/datasets/cifar10_noaug.py
mmagic/configs/_base_/datasets/imagenet_noaug_128.py
mmagic/configs/_base_/models/biggan/base_biggan_128x128.py
mmagic/configs/biggan/biggan-deep_cvt-hugging-face-rgb_imagenet1k-128x128.py
mmagic/configs/biggan/biggan-deep_cvt-hugging-face_rgb_imagenet1k-256x256.py
mmagic/configs/biggan/biggan-deep_cvt-hugging-face_rgb_imagenet1k-512x512.py
mmagic/configs/biggan/biggan_2xb25-500kiters_cifar10-32x32.py
mmagic/configs/biggan/biggan_ajbrock-sn_8xb32-1500kiters_imagenet1k-128x128.py
mmagic/configs/biggan/biggan_cvt-BigGAN-PyTorch-rgb_imagenet1k-128x128.py

Adapting New Version of config Adapting  BigGAN Algorithm, based on open-mmlab/OpenMMLabCamp#643
MMEngine has introduced a novel configuration mechanism, utilizing which we will perform configuration file adaptation.
* Add 2 config python files in mmagic/configs/_base_/datasets/
* Add 6 config python files in mmagic/configs/biggan/
* Add 1 config python files inmmagic/configs/_base_/models/biggan/  
The output of `config_validate.py`:
The output of `demo.py`:
**Before PR**:
**After PR**:

[CodeCamp2023-643] Add new configs of BigGAN

---

mmagic/configs/_base_/datasets/imagenet_512.py
mmagic/configs/_base_/datasets/imagenet_64.py
mmagic/configs/guided_diffusion/adm-g_ddim25_8xb32_imagenet_256x256.py
mmagic/configs/guided_diffusion/adm-g_ddim25_8xb32_imagenet_512x512.py
mmagic/configs/guided_diffusion/adm-g_ddim25_8xb32_imagenet_64x64.py
mmagic/configs/guided_diffusion/adm_ddim250_8xb32_imagenet_256x256.py
mmagic/configs/guided_diffusion/adm_ddim250_8xb32_imagenet_512x512.py
mmagic/configs/guided_diffusion/adm_ddim250_8xb32_imagenet_64x64.py

add new config for mmagic/guided_diffusion
output of the `config_validate.py` is `True`
output of  Infer Instructions
the output inTest Instructions `python tools/test.py mmagic/configs/guided_diffusion/adm_ddim250_8xb32_imagenet_64x64.py https://download.openmmlab.com/mmgen/guided_diffusion/adm-u-cvt-rgb_8xb32_imagenet-64x64-7ff0080b.pth`
it's show the`label` in  `sample_kwargs` is none（in `adm.py`）,  so i # it,actually ,the config isn't have `label` and ouput is success！
add `mmagic/configs/`
Does the modification introduce …

[CodeCamp2023-648]MMagic 新 config 体验与适配 GuidedDiffusion

---

configs/inst_colorization/README.md
configs/inst_colorization/README_zh-CN.md
mmagic/configs/_base_/default_runtime.py
mmagic/configs/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256.py

add `mmagic/configs/_base_/default_runtime.py`
add `mmagic/configs/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256.py`
- output of `python ./tools/config_validate.py --new mmagic/configs/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256.py --old configs/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256.py --scope mmagic `
- output of `python demo/mmagic_inference_demo.py --model-name inst_colorization --model-config …

[CodeCamp2023-649] MMagic 新 config 体验与适配 Instance Colorization

---

mmagic/apis/inferencers/text2image_inferencer.py

To use negative prompt in text2image inferencer:
```python
from mmagic.apis import MMagicInferencer
editor = …
```

[Enhance] add negative prompt for sd inferencer

---

configs/diffusers_pipeline/README.md
configs/diffusers_pipeline/metafile.yml
configs/diffusers_pipeline/sd_xl_pipeline.py
mmagic/apis/inferencers/__init__.py
mmagic/apis/inferencers/base_mmagic_inferencer.py
mmagic/apis/inferencers/diffusers_pipeline_inferencer.py
mmagic/apis/mmagic_inferencer.py
mmagic/models/archs/__init__.py
mmagic/models/archs/wrapper.py
model-index.yml
tests/test_apis/test_inferencers/test_diffusers_pipeline_inferencer.py

```python
from mmagic.apis import MMagicInferencer
editor = MMagicInferencer(model_name='diffusers_pipeline')
text_prompts …
```

[Feature] Support inference with diffusers pipeline, sd_xl first.

---

tests/test_apis/test_inferencers/test_diffusers_pipeline_inferencer.py

[FIX] mock infer in diffusers pipeline inferencer ut.

---

demo/mmagic_inference_demo.py
demo/mmagic_inference_tutorial.ipynb
mmagic/apis/inferencers/diffusers_pipeline_inferencer.py
mmagic/apis/mmagic_inferencer.py
tests/test_apis/test_inferencers/test_diffusers_pipeline_inferencer.py

Some users complain that 'model_setting' is ambiguous， so we add 'config_name' as a supplement.
```python
import mmcv …
```

[Enhance] Add ‘config_name' as a supplement to the 'model_setting'

---

mmagic/configs/real_basicvsr/realbasicvsr_c64b20_1x30x8_8xb1_lr5e_5_150k_reds.py
mmagic/configs/real_basicvsr/realbasicvsr_wogan_c64b20_2x30x8_8xb2_lr1e_4_300k_reds.py

Add new configs of Real BasicVSR
- The output of `config_validate.py`
- The output of `test.py` (only use the folder `000` of VideoLQ for test)

[CodeCamp2023-653] Add new configs of Real BasicVSR

---

mmagic/datasets/transforms/random_degradations.py
mmagic/models/editors/deblurganv2/deblurganv2_generator.py

[Fix] Increase docstring coverage

---

mmagic/__init__.py
tests/test_models/test_archs/test_tokenizer.py

It seems that 'hello' will be added a ' ' in front of it  when tokenizer decodes, it becomes ' hello'. So I replace 'hello' to others words.
If this PR introduces a new feature, it is better to list some use cases …

[Fix] Fix test tokenizer

---

tools/test.py

support `--local-rank` args for PyTorch >= 2.0.0 when performing test.
copy args configure from `tools/train.py` to `tools/test.py`
No.
No new feature introduced. …

[Fix] --local-rank for PyTorch >= 2.0.0

---

projects/powerpaint/gradio_PowerPaint.py
projects/powerpaint/gradio_PowerPaint_ControlNet.py
projects/powerpaint/pipeline/pipeline_PowerPaint.py
projects/powerpaint/pipeline/pipeline_PowerPaint_ControlNet.py
projects/powerpaint/utils/utils.py

PowerPaint

---

projects/powerpaint/README.md
projects/powerpaint/gradio_PowerPaint.py
projects/powerpaint/requirements.txt

[Fix] add openxlab link to powerpaint

---

projects/powerpaint/README.md
projects/powerpaint/gradio_PowerPaint.py

[Enhance] add outpainting to gradio_PowerPaint.py

---

configs/swinir/swinir_x2s48w8d6e180_8xb4-lr2e-4-500k_div2k.py

`ValLoop` does not work well in mmagic and the training expects the validation to have certain methods/attributes only supported in `MultiValLoop` and not in `ValLoop`.
If so, please describe how it breaks the compatibility and how the downstream projects should modify …

[Fix]Update swinir_x2s48w8d6e180_8xb4-lr2e-4-500k_div2k.py, use MultiValLoop.

---

docs/en/advanced_guides/data_preprocessor.md
docs/zh_cn/advanced_guides/data_preprocessor.md

Update data_preprocessor.md
**Before PR**:
**After PR**:

[MMSIG] [Doc] Update data_preprocessor.md

---

mmagic/models/editors/stylegan2/stylegan2_discriminator.py

In file: stylegan2_discriminator.py, method: `__init__`, a logical expression uses the identity operator. A new object is created inside the identity check operation and then used for matching identity. Since this is a distinct, new object, it will not have identity an match with anything else. As a result, the identity check will have a logical short circuit and the program may have unintended behavior. 
The following binary operation
data_aug is not dict()
compares a newly created object with the identity operator which will always evaluate to True.
I suggested that the logical operation should be reviewed for correctness. 
Sponsorship and Support:
This work is done by the security researchers from OpenRefactory and is supported by the [Open Source Security Foundation …

Fix a test expression that has a logical short circuit.

---

projects/powerpaint/gradio_PowerPaint.py

huggingface delete .bin instead of .safetensors,so i fix to load safetensors
fix to load safetensors
None
None
**Before PR**:
**After PR**:

[Fix] Powerpaint to load safetensors

---

projects/powerpaint/README.md
projects/powerpaint/gradio_PowerPaint.py

Enhance PowerPaint
