codes/models/archs/discriminator_vgg_arch.py

bug fix: linear layer's input channel calculation eq.

bug fix: linear layer's input channel calculation eq.

---

README.md

fixed missing link

---

docs/stat.py

update stat to classify papers

---

docs/config.md
docs/merge_docs.sh

Merge config doc into one page

---

mmedit/datasets/pipelines/matting_aug.py

This enables faster backend such as memcached

Use file_client in CompositeFg

---

.github/workflows/build.yml
mmedit/__init__.py

Signed-off-by: lizz <lizz@sensetime.com>

Bump mmcv version and fix CI

---

mmedit/models/backbones/encoder_decoders/decoders/plain_decoder.py

this pr is used to support dim to export onnx model

[feature]: add feature to support dim export onnx model

---

docs/getting_started.md

Fix broken links in `getting_started.md`.

Fix broken links.

---

README.md
docs/notes.md

Fix link of model_zoo in `README.md` and `notes.md`.

Fix link of model zoo.

---

configs/restorers/basicvsr/README.md
configs/restorers/iconvsr/README.md

Add annotations `[ALGORITHM]` to the README files.

Add annotation to BasicVSR and IconVSR README

---

README.md

remove extra quotation in english readme

---

configs/inpainting/deepfillv1/README.md
configs/inpainting/deepfillv2/README.md
configs/inpainting/global_local/README.md
configs/inpainting/partial_conv/README.md
configs/mattors/dim/README.md
configs/mattors/gca/README.md
configs/mattors/indexnet/README.md
configs/restorers/basicvsr/README.md
configs/restorers/edsr/README.md
configs/restorers/edvr/README.md
configs/restorers/esrgan/README.md
configs/restorers/iconvsr/README.md
configs/restorers/liif/README.md
configs/restorers/srcnn/README.md
configs/restorers/srresnet_srgan/README.md
configs/restorers/tof/README.md
configs/synthesizers/cyclegan/README.md
configs/synthesizers/pix2pix/README.md
docs/stat.py
tools/data/generation/paired-pix2pix/README.md
tools/data/generation/unpaired-cyclegan/README.md
tools/data/inpainting/celeba-hq/README.md
tools/data/inpainting/paris-street-view/README.md
tools/data/inpainting/places365/README.md
tools/data/matting/comp1k/README.md
tools/data/super-resolution/div2k/README.md
tools/data/super-resolution/reds/README.md
tools/data/super-resolution/vimeo90k/README.md

Change tags to comment
1. `[ALGORITHM]` -> to ``
2. `[DATASET]`  to ``
`stat.py` is also changed.

Change tags to comment

---

mmedit/models/backbones/sr_backbones/ttsr_net.py
tests/test_ttsr.py

Final module of Texture Transformer Network for Image Super-Resolution.

[Feature] Add Merge-Features.

---

mmedit/models/__init__.py
mmedit/models/transformers/__init__.py
mmedit/models/transformers/search_transformer.py
tests/test_search_transformer.py

[Feature] Add Search-Transformer.

---

README.md
README_zh-CN.md
configs/restorers/glean/README.md
configs/restorers/glean/glean_cat_16x.py
configs/restorers/glean/glean_ffhq_16x.py

Currently include GLEAN for
1. human face 16x SR
2. cat 16x SR

[Feature] Add config and README for GLEAN

---

mmedit/models/__init__.py
mmedit/models/extractors/__init__.py
mmedit/models/extractors/feedback_hour_glass.py
tests/test_extractors.py

[Feature] Add FeedbackHourglass

---

mmedit/models/backbones/sr_backbones/dic_net.py
tests/test_dic_net.py

[Feature] Add FeedbackBlockCustom.

---

configs/restorers/liif/liif_edsr_norm_c64b16_g1_1000k_div2k.py
configs/restorers/liif/liif_edsr_norm_x2-4_c64b16_g1_1000k_div2k.py

Fix config of LIIF

---

.readthedocs.yml

Fix https://github.com/open-mmlab/mmediting/issues/468

Support all formats in readthedocs

---

mmedit/__init__.py

Signed-off-by: lizz <lizz@sensetime.com>

use version_info of mmcv

---

mmedit/datasets/builder.py

Reference: https://github.com/open-mmlab/mmdetection/pull/5697

[Enhance] Reset resource limit

---

.github/workflows/build.yml
setup.py

Add Python 3.9 to CI

---

configs/inpainting/deepfillv1/deepfillv1_256x256_4x4_celeba.py
configs/inpainting/deepfillv1/deepfillv1_256x256_8x2_places.py
configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_celeba.py
configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_places.py
configs/inpainting/global_local/gl_256x256_8x12_celeba.py
configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_celeba.py
configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_places.py
configs/inpainting/partial_conv/pconv_256x256_stage2_4x2_celeba.py
configs/inpainting/partial_conv/pconv_256x256_stage2_4x2_places.py
docs/configs/config_inpainting.md

[Update] Remove PaviLoggerHook in config

---

README.md
README_zh-CN.md

Deprecate PyTorch 1.3

---

configs/restorers/basicvsr_plusplus/basicvsr_plusplus_c64n7_4x2_300k_vimeo90k_bi.py
configs/restorers/glean/glean_in128out1024_4x2_300k_ffhq_celebahq.py
configs/restorers/tdan/tdan_vimeo90k_bdx4_ft_lr5e-5_800k.py
configs/restorers/tdan/tdan_vimeo90k_bdx4_lr1e-4_400k.py
configs/restorers/tdan/tdan_vimeo90k_bix4_ft_lr5e-5_400k.py
configs/restorers/tdan/tdan_vimeo90k_bix4_lr1e-4_400k.py

To fix problems in #522 and #534.

[Fix] Minor fix of BasicVSR++ and TDAN configuration files

---

mmedit/models/backbones/sr_backbones/dfd_net.py
mmedit/models/restorers/__init__.py
mmedit/models/restorers/dfd.py
tests/test_models/test_backbones/test_sr_backbones/test_dfd_net.py
tests/test_models/test_restorers/test_dfd_model.py

This PR supports the model of DFD.

[Feature] Add DFD

---

tools/data/super-resolution/df2k_ost/README.md
tools/data/super-resolution/df2k_ost/README_zh-CN.md
tools/data/super-resolution/df2k_ost/preprocess_df2k_ost_dataset.py

Real-ESRGAN uses DF2K_OST (1. DIV2K, 2. Flickr 2K, 3. OST) dataset for training
This PR supports DF2K_OST. A script to generate sub-images and create LMDB (for faster IO) is added.

[Feature] Support DF2K_OST Dataset

---

docs/faq.md
docs_zh-CN/faq.md

Tranlate `docs/faq.md` to Chinese.

[Doc] Chinese translation of faq.md

---

mmedit/datasets/base_sr_dataset.py

Make SRDataset compatible with tif format.
This PR is based on following.
https://github.com/open-mmlab/mmediting/blob/master/mmedit/datasets/base_generation_dataset.py#L9-L10

[Feature] add tiff in SRDataset IMG_EXTENSIONS

---

mmedit/models/components/__init__.py
mmedit/models/components/discriminators/__init__.py
mmedit/models/components/discriminators/unet_disc.py
tests/test_models/test_components/test_discriminators/test_unet_disc.py

Real-ESRGAN uses a UNet discriminator with spectral normalization
This PR supports the discriminator used in Real-ESRGAN

[Feature] Add UNetDiscriminatorWithSpectralNorm

---

.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/publish-to-pypi.yml

Follow https://github.com/open-mmlab/mmcv/pull/1537

[CI] Cancel previous runs that are not completed

---

mmedit/datasets/pipelines/random_degradations.py
tests/test_data/test_pipelines/test_random_degradations.py

To fix bugs in 1) RandomBlur and 2) RandomVideoCompression 3) RandomResize
Modify mmedit/datasets/pipelines/random_degradations.py

[Fix] Fix bug in random_degradations

---

docs/en/conf.py
docs/zh_cn/conf.py

Follow https://github.com/open-mmlab/mmocr/pull/655
Since Chinese docs are not ready for the new theme, it is not modified at this moment. Further modification / PR is required.

[Docs] update docs/conf.py to use shared items

---

docker/Dockerfile

[Fix] ARG MMCV

---

tests/test_data/test_pipelines/test_loading.py

Related to this. https://github.com/open-mmlab/mmediting/issues/751
There is a duplicate test code to check the result.

Delete duplicate test in loading

---

setup.py

Adding correct keywords and classifiers optimize searching in https://pypi.org/.
Suggestions are welcome.

[Improve] Update keyword and classifier for setuptools

---

CITATION.cff
README.md
README_zh-CN.md

If cite from github :
```bibtex
@software{MMEditing_Contributors_MMEditing_OpenMMLab_Image_2022,
author = {{MMEditing Contributors}},
license = {Apache-2.0},
month = {3},
title = {{MMEditing: OpenMMLab Image and Video Editing Toolbox}},
url = {https://github.com/open-mmlab/mmediting},
version = {0.13.0},
year = {2022}
}
```
```APA
MMEditing Contributors. (2022). MMEditing: OpenMMLab Image and Video Editing Toolbox (Version 0.13.0) [Computer software]. https://github.com/open-mmlab/mmediting
```

[Docs] Update citation

---

docs/en/quick_run.md
docs/zh_cn/quick_run.md
tools/dist_test.sh
tools/dist_train.sh

Reference: https://github.com/open-mmlab/mmselfsup/pull/232

[Enhance] Support dist_train without slurm

---

README.md

fix model zoo link

---

mmedit/__init__.py

MMCV will update in this month

[Improve] Update MMCV_MAX to 1.6

---

demo/restoration_demo.py

[Fix] Change `-` to `_` for `restoration_demo.py`

---

requirements/docs.txt

recommonmark is already replaced by myst

[Fix] Remove recommonmark in requirements/docs.txt

---

README.md
README_zh-CN.md

[Fix] Move EDVR to VSR category in README.md

---

mmedit/datasets/pipelines/crop.py

fix a ValueError's display error

[Fix] Remove `,` in multi-line F-string in `crop.py`

---

docker/README.md

To avoid missing it when update docs

[Docs] Create README.md for docker

---

tools/data/super-resolution/df2k_ost/README.md
tools/data/super-resolution/df2k_ost/README_zh-CN.md

[Docs] Update instruction to OST dataset

---

demo/inpainting_demo.py
demo/matting_demo.py
demo/video_interpolation_demo.py
docs/en/demo.md
docs/zh_cn/demo.md
mmedit/apis/__init__.py
mmedit/apis/inference.py
mmedit/apis/inpainting_inference.py
mmedit/apis/matting_inference.py
mmedit/apis/restoration_face_inference.py
mmedit/apis/restoration_inference.py
mmedit/apis/restoration_video_inference.py
mmedit/apis/video_interpolation_inference.py

1. fix model registry in init_model
2. use checkpoint link in all demo
3. fix config file path

[Fix] fix model registry and docs in demo

---

mmedit/__init__.py

[Improve] Update MMCV_MAX to 2.0

---

mmedit/transforms/matting/crop.py
mmedit/transforms/matting/fgbg.py
tests/test_transforms/test_matting_transforms/test_matting_crop.py

Pathlib will replace  // to / so that ceph paths becomes un available.

[Fix] A bug in RandomResizeBg

---

.github/workflows/build-windows.yml
.github/workflows/build.yml
.github/workflows/lint.yml
.github/workflows/publish-to-pypi.yml
mmedit/models/inpaintors/pconv_inpaintor.py

[Fix] using tensor.repeat instead of tensor.tile due to updated torch version
[Refactor] disable github ci

[Fix] Fix bugs caused by refactoring to pass CI

---

.dev_scripts/download_models.py
.dev_scripts/test_benchmark.py
tools/test.py

```bash
python .dev_scripts/download_models.py --checkpoint-root ./work_dirs/checkpoints/
python .dev_scripts/test_benchmark.py mm_lol ./work_dirs/checkpoints  --use-ceph-config --run 
python .dev_scripts/test_benchmark.py mm_lol ./work_dirs/checkpoints  --summary
```

[Enhancement] Revise test benchmark and download script

---

configs/basicvsr/basicvsr_2xb4_vimeo90k-bd.py
mmedit/models/editors/liif/liif_net.py
mmedit/models/editors/ttsr/ttsr.py

1. configs of Vid4 for validation
2. data type cast in liif for amp training

[Fix] config and liif

---

docs/en/advanced_guides/dataset.md
docs/en/advanced_guides/transforms.md
docs/en/migration.md
docs/en/model_zoo.md
docs/en/notes/contribution_guide.md
docs/en/notes/faq.md
docs/en/notes/projects.md
docs/en/user_guides/config.md
docs/en/user_guides/config/config_inpainting.md
docs/en/user_guides/config/config_matting.md
docs/en/user_guides/config/config_restoration.md
docs/en/user_guides/datasets/dataset_prepare.md
docs/en/user_guides/datasets/inpainting_datasets.md
docs/en/user_guides/datasets/super_resolution_datasets.md
docs/en/user_guides/datasets/video_interpolation_datasets.md
docs/en/user_guides/visualization.md

1. config, datasets and visualization of user_guides
2. advanced_guides/transforms.md
3. advanced_guides/dataset.md
4. advanced_guides/losses.md
5. migration.md
6. model_zoo.md
7. notes: contribution, faq, projects

[Docs] fix docs

---

mmedit/evaluation/metrics/niqe.py

[Improve] Use relpath for NIQE params

---

.circleci/test.yml
mmedit/__init__.py
mmedit/version.py
requirements/mminstall.txt
requirements/readthedocs.txt
requirements/runtime.txt

Bump to version V1.0.0rc0

---

README.md

I made a change to the readme.

supports not support

---

requirements/tests.txt

Add the install requirements of facexlib to enable face restoration.
**Before PR**:
**After PR**:

[Fix] update requirements to install facexlib

---

requirements/tests.txt
tests/test_apis/test_restoration_face_inference.py

- bump to v0.15.2
- update github actions and circleci
- fix ut 
**Before PR**:
**After PR**:

bump to v0.15.2

---

docs/en/changelog.md
docs/zh_cn/changelog.md
mmedit/version.py

Release v0.15.1
update changelog.md and version. 
**Before PR**:
**After PR**:

Release v0.15.2

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/5-reimplementation.yml

fix issue template
fix issue template
**Before PR**:
**After PR**:

[Fix] fix issue template

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/4-documentation.yml
.github/ISSUE_TEMPLATE/5-reimplementation.yml

Fix template
Fix template
**Before PR**:
**After PR**:

Fix template

---

.github/ISSUE_TEMPLATE/1-bug-report.yml

Update 1-bug-report.yml
Update 1-bug-report.yml
**Before PR**:
**After PR**:

[Fix] Update 1-bug-report.yml

---

docs/en/user_guides/5_visualization.md

[Doc] user_guides/5_visualization

---

docs/en/2_get_started.md

update installation scripts
update installation scripts in get_started.md
Does the modification introduce changes that break the backward compatibility of the downstream repositories?
If this PR introduces a new feature, it is better to list some use cases here and update the documentation.
**Before PR**:
**After PR**:

[Documentation] update intallation scripts

---

mmedit/apis/inference.py
mmedit/datasets/grow_scale_image_dataset.py
mmedit/engine/hooks/ema.py
mmedit/models/base_models/two_stage.py
mmedit/models/data_preprocessors/batch_process.py
mmedit/models/data_preprocessors/gen_preprocessor.py
mmedit/models/editors/aotgan/aot_encoder_decoder.py
mmedit/models/editors/basicvsr/basicvsr_net.py
mmedit/models/editors/biggan/biggan.py
mmedit/models/editors/dcgan/dcgan.py
mmedit/models/editors/deepfillv1/deepfillv1.py
mmedit/models/editors/dic/dic_net.py
mmedit/models/editors/flavr/flavr.py
mmedit/models/editors/flavr/flavr_net.py
mmedit/models/editors/ggan/ggan.py
mmedit/models/editors/iconvsr/iconvsr_net.py
mmedit/models/editors/real_basicvsr/real_basicvsr_net.py
mmedit/models/editors/sagan/sagan.py
mmedit/models/editors/stylegan1/stylegan1.py
mmedit/models/editors/tdan/tdan_net.py
mmedit/models/editors/ttsr/lte.py
mmedit/models/editors/ttsr/search_transformer.py
mmedit/models/losses/clip_loss.py
mmedit/models/losses/face_id_loss.py
mmedit/models/losses/loss_comps/clip_loss_comps.py
mmedit/models/losses/loss_comps/face_id_loss_comps.py
mmedit/models/utils/tensor_utils.py
mmedit/utils/io_utils.py
mmedit/visualization/concat_visualizer.py
mmedit/visualization/vis_backend.py

[Doc] fix docstring warnings

---

docs/en/advanced_guides/5_metrics.md
docs/en/index.rst
docs/en/user_guides/8_metrics.md

[Doc] advanced_guides/5_metrics

---

docs/en/advanced_guides/1_models.md

[Doc] advanced-guides/1_models

---

docs/en/3_model_zoo.md

[Doc] model_zoo

---

tests/test_models/test_editors/test_dcgan/test_dcgan.py
tests/test_models/test_editors/test_ggan/test_ggan.py
tests/test_models/test_editors/test_sagan/test_sagan.py

[Enhancement] Add unit test for GAN models

---

tests/test_evaluation/test_metrics/test_equivariance.py

[Fix] Skip unit test of Eq when torch < 1.8.0

---

mmedit/evaluation/evaluator.py
tests/test_evaluation/test_evaluator.py

[Enhancement] Add unit test for evaluator

---

mmedit/engine/hooks/iter_time_hook.py
tests/test_engine/test_hooks/test_iter_time_hook.py
tests/test_engine/test_runner/test_loops.py

[Enhancement] Add unit test for loops + IterTimeHook (mmedit/engine/*.py)

---

mmedit/models/__init__.py
mmedit/models/base_models/base_gan.py
tests/test_models/test_base_models/test_base_conditional_gan.py
tests/test_models/test_base_models/test_base_gan.py

[Enhancement] Add unit tests for BaseGAN and BaseConditionalGAN

---

docs/en/2_get_started.md

From 69 to 82, it is not related to Step 5 but related to Step 4. I think we should put it to Step 4 or create a new subsection as notion to include this part.

Review by Wu Bohuai

---

configs/biggan/README.md
configs/cyclegan/README.md
configs/dcgan/README.md
configs/ggan/README.md
configs/lsgan/README.md
configs/pggan/README.md
configs/pix2pix/README.md
configs/sagan/README.md
configs/singan/README.md
configs/sngan_proj/README.md
configs/styleganv1/README.md
configs/styleganv2/README.md
configs/styleganv3/README.md
configs/wgan-gp/README.md

[Doc] update task label in README

---

docs/en/advanced_guides/4_losses.md

[Doc] update losses.md

---

.dev_scripts/update_ut.py
tests/test_models/test_editors/test_stylegan3/test_stylegan3_utils.py

[Fix] Fix stylegan3 ut

---

configs/biggan/README.md
configs/biggan/metafile.yml
tests/test_models/test_editors/test_stylegan2/test_stylegan2_generator.py

[Fix] Fix lint after merge

---

configs/_base_/models/base_edvr.py
configs/basicvsr/basicvsr_2xb4_reds4.py
configs/basicvsr_pp/basicvsr-pp_c64n7_8xb1-600k_reds4.py
configs/cyclegan/cyclegan_lsgan-id0-resnet-in_1xb1-250kiters_summer2winter.py
configs/deepfillv1/deepfillv1_4xb4_celeba-256x256.py
configs/deepfillv1/deepfillv1_8xb2_places-256x256.py
configs/deepfillv2/deepfillv2_8xb2_celeba-256x256.py
configs/deepfillv2/deepfillv2_8xb2_places-256x256.py
configs/dim/dim_stage1-v16_1xb1-1000k_comp1k.py
configs/edvr/edvrl_c128b40_8xb8-lr2e-4-600k_reds4.py
configs/edvr/edvrl_wotsa-c128b40_8xb8-lr2e-4-600k_reds4.py
configs/edvr/edvrm_8xb4-600k_reds.py
configs/edvr/edvrm_wotsa_8xb4-600k_reds.py
configs/partial_conv/pconv_stage1_8xb1_celeba-256x256.py
configs/partial_conv/pconv_stage1_8xb1_places-256x256.py
configs/partial_conv/pconv_stage2_4xb2_celeba-256x256.py
configs/partial_conv/pconv_stage2_4xb2_places-256x256.py

[Fix] replace lr_config by param_scheduler

---

mmedit/datasets/transforms/generate_assistant.py

[Fix] fix trans_utils import error

---

.dev_scripts/README.md
README.md
README_zh-CN.md

update links in readme
update links in readme
**Before PR**:
**After PR**:

[Fix] readme

---

tests/test_models/test_editors/test_iconvsr/test_iconvsr_net.py

[Enhancement] Add CPU unit test for IconVSR

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml
.github/workflows/publish-to-pypi.yml
setup.py

[Enhancement] Update setup and publish workflow

---

mmedit/engine/hooks/__init__.py
mmedit/engine/hooks/pickle_data_hook.py
tests/test_engine/test_hooks/test_pickle_data_hook.py

[Feature] Add pickle data hook

---

.github/workflows/merge_stage_test.yml

[Fix] Fix merge stage test

---

.github/workflows/merge_stage_test.yml

[Fix] Fix PyTorch installation in merge stage test

---

.github/pull_request_template.md
.owners.yml

update github-bot setting and pr template.
update github-bot setting and pr template. 
**Before PR**:
**After PR**:

[Enhance] update setting

---

docs/en/conf.py
docs/zh_cn/conf.py

[Enhancement] add version switcher to the docs menu

---

mmedit/models/__init__.py
mmedit/models/video_interpolators/__init__.py

`FLAVR` is missing in `mmedit.models.__init__.py` and `mmedit.models.video_interpolators.__init__.py`.
Refers to #1003 .
Import `FLAVR` in  `mmedit.models.__init__.py` and `mmedit.models.video_interpolators.__init__.py`.
If this PR introduces a new feature, it is better to …

[Fix] Fix FLAVR register

---

mmedit/evaluation/metrics/ppl.py
mmedit/utils/io_utils.py

Fix injected noise.
**Before PR**:
**After PR**:

[Fix] Fix PPL bug

---

.github/ISSUE_TEMPLATE/3-new-model.yml

using "feature-request" as the default label for new-model template.
using "feature-request" as the default label for new-model template.
**Before PR**:
**After PR**:

[Docs] Update 3-new-model.yml

---

configs/_base_/datasets/sisr_x2_test_config.py
configs/_base_/datasets/sisr_x3_test_config.py
configs/_base_/datasets/sisr_x4_test_config.py
configs/partial_conv/pconv_stage1_8xb1_celeba-256x256.py
configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py

[Fix]  Fix bugs in `sr test config`, `realbasicvsr config` and `pconv config`

---

mmedit/evaluation/evaluator.py
tests/test_evaluation/test_evaluator.py

[Feature] Support multi-metrics with different sample-model

---

.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/3-new-model.yml
.github/ISSUE_TEMPLATE/4-documentation.yml

Add a default label "awaiting response" which corresponds to "have not started" in our develop habits.
So that when we start to deal with that PR/issue, we can set the label to "WIP"
You can find the result here: https://github.com/zengyh1900/mmediting/issues
Add a default label "awaiting response"  to each template.
If so, please describe how it breaks the compatibility and how the downstream projects should modify …

[Enhancement] improve issue template

---

tests/test_datasets/test_transforms/test_generate_frame_indices.py

Add  generate_frame_indices.py ut coverage.
Add ut case in test_generate_frame_indices.py
**Before PR**:
**After PR**:

[Fix] fix GenerateSegmentIndices ut

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

Windows CI of GitHub workflow break down.
Convert `pip xxx` to `python -m pip xxx`.
**Before PR**:
**After PR**:

[CI] Fix GitHub windows CI

---

configs/_base_/datasets/sisr_x3_test_config.py
configs/_base_/datasets/sisr_x4_test_config.py

fix sisr-test psnr config, which influences psnr results of edsr, esrgan, rdb, srcnn, srgan.
sisr-test config: psnr crop_border setting
**Before PR**:
**After PR**:

[Fix] fix sisr-test psnr config

---

mmedit/datasets/transforms/generate_assistant.py

`GenerateFacialHeatmap` may return a `np.float64` array, and make part of loss terms become `torch.float64` and leads to backward error.
Convert heatmap to `np.float32` at the end of `GeneratFacialHeatmap`.
If this PR introduces a new feature, it is better to list some use …

[Bug] Ensure the output type of `GenerateFacialHeatmap` is `np.float32`

---

configs/ttsr/README.md
configs/ttsr/metafile.yml

The header of TTSR's README has two SSIM columns and no PSNR column.
Fix the header of TTSR's README.
**Before PR**:
**After PR**:

[README] Fix TTSR's README

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

GitHub run CI for README files and this operation take too much time.
Update `paths-ignore` in `pr_stage_test.yml` and `merge_stage_test.yml`. 
**Before PR**:
**After …

[CI] Update `paths-ignore` for GitHub CI

---

mmedit/models/editors/pggan/pggan.py
tests/test_models/test_editors/test_pggan/test_pggan.py

PGGAN's forward forget to save gt images.
Save real images to `data_sample.gt_img`. 
**Before PR**:
**After PR**:

[Bug] Save gt images in PGGAN's `forward`

---

configs/_base_/datasets/cifar10_nopad.py
configs/_base_/datasets/imagenet_128.py

The `keys` keyword is missing in the `Flip` transformation for `cifar_no_pad.py` and `imagenet_128.py`.
Add the `keys` keyword to `Flip`.
**Before PR**:
**After PR**:

[Bug] Revise flip transformation in some conditional gan's setting

---

tests/test_evaluation/test_metrics/test_snr.py

The unit tests of SNR metric (`test_snr.py`) test `PSNR` metric in `test_snr` function.
Fix `test_snr` function.
**Before PR**:
**After PR**:

[Unit Test] Fix unit test of SNR

---

configs/flavr/flavr_in4out1_8xb4_vimeo90k-septuplet.py

FLAVR use `EpochBasedLoop` but sets the train dataloader's sampler as `InfinitySampler`, which leads to an endless training process.
Change `InfinitySampler` to `DefaultSampler`. …

[Bug] Revise flavr config

---

.dev_scripts/metric_mapping.py
.dev_scripts/train_benchmark.py
mmedit/models/editors/__init__.py
mmedit/models/editors/stylegan1/stylegan1.py

Fix some bugs for bug-free benchmark running.
**Before PR**:
**After PR**:

[Fix] Fix bugs find during benchmark running

---

configs/_base_/datasets/liif_test_config.py

In liif test config, psnr crop-border is wrong
Ser crop-border = scale
**Before PR**:
**After PR**:

[Fix] fix liif test config

---

mmedit/models/editors/disco_diffusion/secondary_model.py

support secondary model in disco-diffusion

---

configs/edsr/edsr_x2c64b16_1xb16-300k_div2k.py
configs/edsr/edsr_x3c64b16_1xb16-300k_div2k.py
configs/edsr/edsr_x4c64b16_1xb16-300k_div2k.py

Fix edsr train configs bugs
Set configs as same as MMEdit 0.x
**Before PR**:
**After PR**:

[Fix] fix edsr configs

---

mmedit/visualization/gen_visualizer.py

Pixel value clamping in `GenVisualizer` is missing.
Add pixel value clamp.
**Before PR**:
**After PR**:

[Enhancement] Add pixel value clip in visualizer

---

configs/_base_/datasets/paired_imgs_256x256_crop.py
configs/_base_/models/base_pix2pix.py
configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-220kiters_aerial2maps.py
configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-220kiters_maps2aerial.py
configs/pix2pix/pix2pix_vanilla-unet-bn_1xb1-80kiters_facades.py
configs/pix2pix/pix2pix_vanilla-unet-bn_wo-jitter-flip-4xb1-190kiters_edges2shoes.py
mmedit/models/base_models/base_translation_model.py
mmedit/models/editors/pix2pix/pix2pix.py

Pix2Pix models in MMEditing-1.x have the following bugs:
1. Behavior of `FixedCrop` in `TransformBroadcaster` is different for input image pairs.
2. L1 loss is missing in Pix2Pix model
1. Config modification: Remove `TransformBroadcaster`
2. Add L1 loss
If this PR introduces …

[Bug] Fix randomness in FixedCrop + add L1 loss in Pix2Pix

---

configs/real_basicvsr/realbasicvsr_c64b20-1x30x8_8xb1-lr5e-5-150k_reds.py
configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py

Align real-basicvsr test metrics.
Fix realbasicvsr config
**Before PR**:
**After PR**:

[Fix] fix realbasicvsr config

---

.github/ISSUE_TEMPLATE/config.yml
.owners.yml

updata daily assignees; fix typo
1. updata daily assignees @liuwenran 
2. fix typo in issue forms
**Before PR**:
**After PR**:

[Enhancement] updata daily assignees; fix typo

---

configs/inpainting/AOT-GAN/AOT-GAN_512x512_4x12_places.py
configs/inpainting/deepfillv1/deepfillv1_256x256_4x4_celeba.py
configs/inpainting/deepfillv1/deepfillv1_256x256_8x2_places.py
configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_celeba.py
configs/inpainting/deepfillv2/deepfillv2_256x256_8x2_places.py
configs/inpainting/global_local/gl_256x256_8x12_celeba.py
configs/inpainting/global_local/gl_256x256_8x12_places.py
configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_celeba.py
configs/inpainting/partial_conv/pconv_256x256_stage1_8x1_places.py
configs/inpainting/partial_conv/pconv_256x256_stage2_4x2_celeba.py
configs/inpainting/partial_conv/pconv_256x256_stage2_4x2_places.py
docs/en/configs/config_inpainting.md
docs/zh_cn/configs/config_inpainting.md
mmedit/core/__init__.py
mmedit/core/hooks/__init__.py
mmedit/core/hooks/visualization.py
mmedit/utils/__init__.py
mmedit/utils/misc.py
tests/test_runtime/test_visual_hook.py
tests/test_utils/test_misc.py

As issue #331 .
Rename `VisualizationHook` to `MMEditVisualizationHook`, and add a warning when the user builds `VisualizationHook`.
**Before PR**:
**After PR**:

[Enhancement] Rename VisualizationHook to MMEditVisualizationHook

---

tools/data/super-resolution/div2k/preprocess_div2k_dataset.py

[Fix]: add type and change default number in preprocess_div2k_dataset.py

---

configs/_base_/datasets/paired_imgs_256x256_crop.py
configs/_base_/datasets/unpaired_imgs_256x256.py
configs/_base_/gen_default_runtime.py
configs/_base_/matting_default_runtime.py
configs/ggan/ggan_dcgan-archi_lr1e-3-1xb128-12Mimgs_celeba-cropped-64x64.py
configs/ggan/ggan_dcgan-archi_lr1e-4-1xb64-10Mimgs_celeba-cropped-128x128.py

Revise GGAN's evaluation config. `default_gen_runtime` is revised as well.
Update configs.
**Before PR**:
**After PR**:

[Config] Update metric config in ggan

---

README.md
README_zh-CN.md
docs/en/changelog.md
docs/zh_cn/changelog.md
mmedit/__init__.py
mmedit/version.py

bump to v0.16.0
bump to v0.16.0
**Before PR**:
**After PR**:

bump to v0.16.0

---

tools/dataset_converters/super-resolution/div2k/preprocess_div2k_dataset.py

python tools/dataset_converters/super-resolution/div2k/preprocess_div2k_dataset.py --data-root ./data/DIV2K
**Before PR**: …

[Fix]: add type and change default number of preprocess_div2k_dataset.py

---

configs/positional_encoding_in_gans/mspie-stylegan2-config-c_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-d_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-e_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-f_c1_8xb2-1600kiters_ffhq-256-1024.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-f_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-f_c2_8xb3-1100kiters_ffhq-256-896.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-g_c1_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-h_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-i_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-j_c2_8xb3-1100kiters_ffhq-256-512.py
configs/positional_encoding_in_gans/mspie-stylegan2-config-k_c2_8xb3-1100kiters_ffhq-256-512.py

The test pipeline should resize image to 256x256 with opencv backend. The original one lack these. …

[Fix] Fix test/val pipeline of pegan configs

---

configs/styleganv3/README.md

Since training is finished and metric is aligned, remove the note.
**Before PR**:
**After PR**:

[Fix] Modify Readme of S3

---

configs/lsgan/lsgan_lsgan-archi_lr1e-4-1xb64-10Mimgs_lsun-bedroom-128x128.py

A change to fid:
```python
real_nums=50000,
inception_style='PyTorch',
```
**Before PR**:
**After PR**:

[Fix] Fix lsgan config

---

configs/styleganv2/stylegan2_c2_8xb4_lsun-car-384x512.py
mmedit/evaluation/functional/inception_utils.py

[Enhancement] Set ``real_feat`` to cpu in inception_utils

---

.circleci/test.yml
.github/workflows/pr_stage_test.yml
mmedit/models/losses/clip_loss.py
requirements.txt
requirements/optional.txt
requirements/runtime.txt

`clip` is only used for `ClipLoss`, and this should an optional dependency.
Add `clip` to `optional.txt` and add `try_import` in `ClipLossModel`.
**Before PR**: …

[Enhancement] Support try-import for `clip`

---

README.md
README_zh-CN.md
docs/en/notes/3_changelog.md
mmedit/version.py

[Doc] Update changelog and README for 1.0.0rc3.

---

.github/workflows/merge_stage_test.yml

[Bug] Install clip in merge stage test

---

.github/workflows/merge_stage_test.yml

[Fix] Install clip in windows CI

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

`pip` failure in windows CI.
Convert `pip` to `python -m pip` in windows CI.
**Before PR**:
**After PR**:

[Fix] Fix windows CI for master

---

requirements/readthedocs.txt

Readthedoc build failed.
Add tqdm.
**Before PR**:
**After PR**:

[Doc] fix readthedoc requirements

---

mmedit/engine/hooks/visualization_hook.py
tests/test_engine/test_hooks/test_visualization_hook.py

* `GenVisualizationHook` has bug in the test stage (i.e., all samples are saved as 'fake_0.png').
* `GenVisualizationHook` save all samples during the test. This cost too much hard disk quota.
Revise `after_test_iter` and support `max_save_at_test` feature (save 100 samples as default).
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility …

[Enhancement] Fix 'after_test_ite' of vis hook + support 'max_save_at_test'

---

tests/test_engine/test_runner/test_log_processor.py

MMEngine changes the behavior of `LogProcessor`.
Fix ut of `LogProcessor`.
**Before PR**:
**After PR**:

[Fix] Revise unit test of log processor

---

configs/_base_/datasets/grow_scale_imgs_ffhq_styleganv1.py
configs/_base_/datasets/unconditional_imgs_128x128.py
configs/pggan/pggan_8xb4-12Mimgs_celeba-cropped-128x128.py
docs/en/dataset_zoo/5_unconditional_gans_datasets.md
docs/en/user_guides/1_config.md
docs/en/user_guides/4_train_test.md
tools/dataset_converters/unconditional_gans/README.md

[Refactor] Replace UnconditionalImageDataset with BasicImageDataset

---

docs/en/1_overview.md
docs/en/2_get_started.md
docs/en/3_model_zoo.md

[Docs] Refine dev-1.x docs

---

tests/test_models/test_base_models/test_two_stage.py
tests/test_models/test_editors/test_aotgan/test_aot_inpaintor.py
tests/test_models/test_editors/test_deepfillv2/test_two_stage_encoder_decoder.py
tests/test_models/test_editors/test_pconv/test_pconv_inpaintor.py

In MMEngine v0.3.2, `_` is removed from `data samples's element.
Revise unit test related to data samples.
**Before PR**:
**After PR**:

[Fix] Adopt ut with newest mmengine

---

mmedit/models/base_models/base_conditional_gan.py

[bug] Update base_conditional_gan.py

---

docs/en/user_guides/3_inference.md

update cmd config
update cmd config
**Before PR**:
**After PR**:

[bug] fix 1.x face demo readme config error

---

mmedit/evaluation/metrics/ppl.py
mmedit/models/editors/eg3d/camera.py
mmedit/models/utils/__init__.py
mmedit/models/utils/tensor_utils.py
tests/test_models/test_editors/test_eg3d/test_camera.py
tests/test_models/test_utils/test_tensor_utils.py

EG3D needs a camera class to sample input conditions (camera-to-world matrix and intrinsic matrix).
Support a few camera classes.
**Before PR**:
**After PR**:

[Feature] Support camera class for EG3D

---

mmedit/models/editors/eg3d/math_utils.py
mmedit/models/editors/eg3d/renderer.py
tests/test_models/test_editors/test_eg3d/test_renderer.py

Support a renderer.
Support a renderer. 
**Before PR**:
**After PR**:

[Feature] Support EG3D renderer

---

mmedit/models/editors/eg3d/ray_sampler.py
tests/test_models/test_editors/test_eg3d/test_ray_sampler.py

EG3D uses a ray sampler to sample rays. In our implementation, we simplify it to a sample function.
Support ray sampler.
**Before PR**:
**After PR**:

[Feature] Support ray sampler for EG3D

---

mmedit/models/editors/eg3d/eg3d_modules.py
tests/test_models/test_editors/test_eg3d/test_eg3d_modules.py

Add modules used in EG3D.
Add `TriPlaneBackbone`, `SuperResolutionModule`, and `SynthesisModule`.
This PR relies on #1443.
**Before PR**:
**After PR**:

[Feature] Add EG3D modules

---

mmedit/models/editors/eg3d/eg3d_generator.py
tests/test_models/test_editors/test_eg3d/test_eg3d_generator.py

Support TriPlane Generator for EG3D.
Support TriPlane Generator for EG3D.
This PR relies on #1458.
**Before PR**:
**After PR**:

[Feature] Support TriPlane Generator for EG3D.

---

mmedit/models/editors/eg3d/camera.py
tests/test_models/test_editors/test_pconv/test_pconv_inpaintor.py
tests/test_models/test_editors/test_pggan/test_pggan_discriminator.py
tests/test_models/test_editors/test_ttsr/test_ttsr_disc.py
tests/test_models/test_editors/test_ttsr/test_ttsr_net.py

Pytorch <= 1.6.0 does not have `torch.arccos`.
Use `np.arccos` in camera for Pytorch <= 1.6.0.
**Before PR**:
**After PR**:

[Fix] Support arccos in camera for torch <= 1.6

---

README.md
README_zh-CN.md
docs/en/notes/3_changelog.md
mmedit/version.py

As title.
**Before PR**:
**After PR**:

[Enhancement] Add EG3D and Disco to README

---

configs/disco_diffusion/tutorials.ipynb

Fix disco notebook

---

tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion.py

The code structure for Disco Diffusion's Unit test is wrong.
Fix disco diffusion's unit test.
**Before PR**:
**After PR**:

[Enhancement] Fix unit test for disco diffusion

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml

Add torch 1.13 checking in CI.
Add torch 1.13 checking in CI.
**Before PR**:
**After PR**:

[Enhancement] Add torch1.13 checking in CI

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml
requirements/runtime.txt
requirements/tests.txt

In CI, some packages are installed by `pip install -r requirements/tests.txt` and some are installed manually. In this PR, all dependencies are integrated to `tests.txt`.
1. Add some optional packages to `tests.txt`
2. Remove `torch` and `torchvision` from `runtime.txt`.
If …

[Enhanchement] Revise test requirements and CI

---

configs/biggan/README.md

BigGAN 128x128 hard to reproduce with A100 + cuda11.3.  
Add a reproducibility warning in README.
**Before PR**:
**After PR**:

[Enhancement] Add reproducibility warning for BigGAN 128x128

---

configs/biggan/biggan-deep_cvt-hugging-face_rgb_imagenet1k-256x256.py
configs/biggan/biggan-deep_cvt-hugging-face_rgb_imagenet1k-512x512.py

The original BigGAN config modifies resize scale in the wrong way.
Revise the configs.
**Before PR**:
**After PR**:

revise config of biggan-cvt

---

configs/disco_diffusion/README.md
configs/disco_diffusion/metafile.yml

[fix] fix disco readme

---

requirements/tests.txt

Coverage 7.0 change some APIs.
Use coverage < 7.0.0 in unit test. 
**Before PR**:
**After PR**:

[Enhancement] Use coverage < 7.0.0 in unit tests

---

tests/test_models/test_editors/test_restormer/test_restormer_net.py

Ut failed on torch<1.8
Skip restormer ut on torch<1.8
**Before PR**:
**After PR**:

[Fix] fix restormer ut

---

docs/en/community/contributing.md
docs/en/community/projects.md
projects/README.md

update readme of projects 
**Before PR**:
**After PR**:

update readme of projects 

---

tests/test_models/test_editors/test_cyclegan/test_cyclegan_modules.py

Cover more lines of CycleGAN module's unit test.
Revise the unit test.
**Before PR**:
**After PR**:

[Enhancement] Cover more lines of cyclegan-module's unit test

---

.circleci/test.yml
requirements/runtime.txt
tests/test_apis/test_inferencers/test_inference_functions.py
tests/test_apis/test_inferencers/test_video_restoration_inferencer.py
tests/test_models/test_editors/test_ddpm/test_attention.py
tests/test_models/test_editors/test_ddpm/test_ddpm_scheduler.py
tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion.py
tests/test_models/test_editors/test_stylegan1/test_stylegan1.py
tests/test_models/test_editors/test_stylegan2/test_stylegan2.py

[Fix] fix v1.0.0rc5 ci error

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml
setup.py

[Fix] fix ci follow mmengine

---

.gitignore
configs/stable_diffusion/README.md

[Enhancememt] add more infomation in sd readme

---

mmedit/models/editors/ddpm/denoising_unet.py

[Fix] fix disco bug with glide added.

---

.pre-commit-config.yaml

[Fix] fix lint

---

tests/test_models/test_editors/test_stylegan1/test_stylegan1.py
tests/test_models/test_editors/test_stylegan2/test_stylegan2.py

[Fix] stylegan circleci ut.

---

projects/glide/models/glide.py

[Fix] fix glide bug

---

docs/en/conf.py

[Fix] fix viewcode for API docs

---

mmedit/models/editors/real_esrgan/real_esrgan.py

[Fix] fix load realesrgan ckpt error

---

mmedit/apis/inferencers/mmedit_inferencer.py
mmedit/apis/inferencers/translation_inferencer.py
mmedit/edit.py

[Refact] support all models in translation inferencer

---

mmedit/apis/inferencers/base_mmedit_inferencer.py
mmedit/apis/inferencers/conditional_inferencer.py
mmedit/edit.py

[Enhancement] support all conditional models inference.

---

.pre-commit-config.yaml

[Fix] update isort version

---

mmedit/registry.py

fix the location for `TRANSFORMS` from `mmedit.datasets` to `mmedit.datasets.transforms`
**Before PR**: …

[bugfix] register transforms

---

mmedit/datasets/grow_scale_image_dataset.py
mmedit/models/base_models/base_gan.py
mmedit/models/editors/eg3d/eg3d.py
mmedit/models/editors/mspie/positional_encoding.py
mmedit/structures/edit_data_sample.py

Fix CI for #1656.
Fix lint, unit test to pass CI.
**Before PR**:
**After PR**:

[Fix] Fix CI for `refactor-metric-loop-and-preprocessor`.

---

mmedit/datasets/grow_scale_image_dataset.py
mmedit/datasets/transforms/aug_pixel.py
mmedit/datasets/transforms/crop.py
mmedit/models/editors/guided_diffusion/classifier.py
mmedit/models/editors/inst_colorization/inst_colorization.py
mmedit/structures/edit_data_sample.py

As title.
As title.
**Before PR**:
**After PR**:

[Enhancement] Add more docstring to pass lint checking

---

.dev_scripts/test_benchmark.yml
.dev_scripts/train_benchmark.yml

The test team needs a metafile to run the benchmark. In this PR, we add config metafile for them. 
The selected P0 terms are:
* basicvsr-pp_c64n7_8xb1-600k_reds4
* realbasicvsr_c64b20_1x30x8_lr5e-5_150k_reds
* stylegan2_c2_8xb4-800kiters_ffhq-256x256
* deepfillv1_256x256_8x2_places
* realesrnet_c64b23g32_12x4_lr2e-4_1000k_df2k_ost
Add metafiles.
If so, please describe how it breaks the compatibility and how the …

[Enhancement] Add benchmark configs for test team

---

mmedit/evaluation/metrics/ms_ssim.py

As title.
As title.
**Before PR**:
**After PR**:

[Enhancement] Remove useless comments from MS-SSIM

---

.github/workflows/publish-to-pypi.yml
MANIFEST.in

The previous pre-release has no wheel file uploaded. See more details https://pypi.org/project/mmedit/1.0.0rc5/#files
1. include `niqe_pris_params.npz` in `MENIFEST.in`
2. using `python setup.py sdist bdist_wheel` for building mmedit in deploy-to-pypi
If this PR introduces a …

[fix] fix the issue of deploy-to-pypi without wheel file

---

.circleci/config.yml
configs/guided_diffusion/adm-u_8xb32_imagenet-512x512.py
configs/guided_diffusion/adm_ddim250_8xb32_imagenet-256x256.py
configs/guided_diffusion/adm_ddim250_8xb32_imagenet-512x512.py
configs/guided_diffusion/adm_ddim250_8xb32_imagenet-64x64.py
mmedit/apis/inferencers/colorization_inferencer.py
mmedit/apis/inferencers/inference_functions.py
mmedit/models/editors/inst_colorization/inst_colorization.py
tests/test_apis/test_inferencers/test_translation_inferencer.py
tests/test_models/test_editors/test_cyclegan/test_cyclegan.py
tests/test_models/test_editors/test_guided_diffusion/test_adm.py
tests/test_models/test_editors/test_inst_colorization/test_inst_colorization.py
tests/test_models/test_editors/test_pix2pix/test_pix2pix.py

As title.
1. Adapt `EditDataPreprocessor` for ADM and fix GPU unit test for ADM
2. Fix unit tests and inference for InstColorization
3. Fix GPU unit test for Pix2Pix and CycleGAN …

[Fix] Fix GPU unit test for PR #1656

---

tests/test_engine/test_hooks/test_visualization_hook.py

[Fix] fix visualization hook ut

---

requirements/optional.txt
requirements/tests.txt

[Fix] fix requirements for wheel build

---

requirements/optional.txt
requirements/tests.txt

Bump Version to 1.0.0rc6

---

mmedit/utils/sampler.py
tests/test_engine/test_hooks/test_visualization_hook.py
tests/test_utils/test_sampler.py

This PR fix issue is mentioned in #1688.
As title
**Before PR**:
**After PR**:

[Fix] Fix ValSampler error when use EditValLoop

---

mmedit/models/base_archs/__init__.py
mmedit/models/base_archs/wrapper.py
tests/configs/diffuser_wrapper_cfg/config.json
tests/test_models/test_base_archs/test_wrapper.py

Directly adding diffusers' models to the registry did not allow users to use diffusers' models as MMEditing ones. Therefore we support `DiffuserWrapper` and build a sequence of new classes.
```python
Example:
>>> 1. Load pretrained model from HuggingFace Space.
>>> config = dict(
>>>     type='ControlNetModel',  # has been registered in `MODELS`
>>>     from_pretrained='lllyasviel/sd-controlnet-canny',
>>>     torch_dtype=torch.float16)
>>> controlnet = MODELS.build(config)
>>> 2. Initialize model with pre-defined configs.
>>> …
```

[Enhancement] Support diffuser wrapper

---

configs/_base_/models/base_tof.py

[Fix] fix tof train annotation file

---

configs/nafnet/nafnet_c64eb11128mb1db1111_8xb8-lr1e-3-400k_gopro.py
configs/nafnet/nafnet_c64eb2248mb12db2222_8xb8-lr1e-3-400k_sidd.py

[Fix] fix nafnet optimizer config

---

mmedit/models/base_archs/wrapper.py
tests/configs/diffuser_wrapper_cfg/config.json
tests/test_models/test_base_archs/test_wrapper.py

`DiffusersWrapper` is inherited from `BaseModule`, which has `forward` function. However, when we call `forward`, we actually want to call `DiffusersWrapper.model.forward`.
* Add `forward` for `DiffusersWrapper`. 
* Config used for unit test is slightly modified to save memory cost.
If so, please describe how it breaks the compatibility and how the downstream projects should modify their code to keep compatibility with …

[Fix] Revise the `forward` function for `DiffusersWrapper`.

---

mmedit/models/editors/controlnet/controlnet_utils.py
tests/test_models/test_editors/test_controlnet/test_controlnet_utils.py

As title.
As title.
**Before PR**:
**After PR**:

[Feature] Support convert base model for ControlNet

---

tools/dataset_converters/df2k_ost/README.md
tools/dataset_converters/df2k_ost/README_zh-CN.md
tools/dataset_converters/reds/README.md
tools/dataset_converters/reds/README_zh-CN.md
tools/dataset_converters/udm10/README.md
tools/dataset_converters/vimeo90k/README.md

[Doc] fix typos of datasets docs

---

mmedit/models/backbones/vfi_backbones/tof_vfi_net.py

> Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
Fix warp typo in TOFlow.
I simply change the `wrap_frame` to `warp_frame`. The renamed variables are all local and thus the modification would not influences other functions. …

[Fix] Fix warp typo

---

configs/video_interpolators/tof/tof_vfi_spynet_chair_nobn_1xb1_vimeo90k.py
configs/video_interpolators/tof/tof_vfi_spynet_kitti_nobn_1xb1_vimeo90k.py
configs/video_interpolators/tof/tof_vfi_spynet_pytoflow_nobn_1xb1_vimeo90k.py
configs/video_interpolators/tof/tof_vfi_spynet_sintel_clean_nobn_1xb1_vimeo90k.py
configs/video_interpolators/tof/tof_vfi_spynet_sintel_final_nobn_1xb1_vimeo90k.py

> Thanks for your contribution and we appreciate it a lot. The following instructions would make your pull request more healthy and more easily get feedback. If you do not understand some items, don't worry, just make the pull request and seek help from maintainers.
In the TOFlow configurations for video interpolation, `TOFlowVFI` backbone is indicated. However, there is no `TOFlowVFI` but `TOFlowVFINet`.
I simply change the `TOFlowVFI` to `TOFlowVFINet`. Tests are run successfully.
> Does the modification introduce changes that break the backward-compatibility of the downstream repositories?
No.
> If this PR introduces a new feature, it is …

[Fix] Change TOFlowVFI to TOFlowVFINet

---

mmedit/models/editors/deepfillv1/deepfillv1.py
mmedit/structures/edit_data_sample.py

Deepfillv1 and gl need mask_bbox data
**Before PR**:
**After PR**:

[Fix] Add 'mask_bbox' key in EditDataSample

---

configs/stable_diffusion/README.md

[Fix] add instruction in sd readme

---

mmedit/models/editors/disco_diffusion/guider.py

[Fix] fix clip import error

---

configs/real_basicvsr/realbasicvsr_wogan-c64b20-2x30x8_8xb2-lr1e-4-300k_reds.py
mmedit/edit.py

```
python mmediting_inference_demo.py \
--model-name edvr \
--extra-parameters window_size=5 \
--video input_dir \
--result-out-dir output_dir
python mmediting_inference_demo.py \
--model-name tdan \
--model-setting 2 \
--extra-parameters window_size=5 \
--video input_dir \
--result-out-dir output_dir
python mmediting_inference_demo.py \
--model-name basicvsr \
--video input_dir \
--result-out-dir output_dir
python mmediting_inference_demo.py \
--model-name iconvsr \
--video input_dir \
--result-out-dir output_dir
python …
```

[Enhance] support all Video Super-Resolution models inferencer

---

mmedit/datasets/__init__.py
mmedit/datasets/controlnet_dataset.py
tests/data/controlnet/prompt.json
tests/test_datasets/test_controlnet_dataset.py

As title.
As title.
**Before PR**:
**After PR**:

[Feature] Support demo dataset for ControlNet

---

.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml

[Fix] update github actions to Ubuntu 22.04

---

.circleci/test.yml
.github/workflows/merge_stage_test.yml
.github/workflows/pr_stage_test.yml
.github/workflows/test_mim.yml
README.md
README_zh-CN.md
configs/disco_diffusion/tutorials.ipynb
docs/en/get_started/install.md
mmedit/datasets/transforms/crop.py
requirements/mminstall.txt
requirements/optional.txt
requirements/readthedocs.txt
requirements/tests.txt

[Enhancement] update version dependency

---

.github/workflows/merge_stage_test.yml

[Fix] fix torch min version of ci

---

docs/en/conf.py
docs/zh_cn/conf.py

[Doc] update docs conf branch

---

.circleci/test.yml

[Fix] fix circle ci minimum gpu

---

mmedit/models/editors/disco_diffusion/disco.py
mmedit/models/editors/disco_diffusion/guider.py
mmedit/models/editors/stylegan2/ada/upfirdn2d.py

[Fix] fix 1.0.0rc7ut

---

tests/test_models/test_editors/test_controlnet/test_controlnet.py

Memory Limitation.
As title.
**Before PR**:
**After PR**:

[Fix] Skip unit test of ControlNet on windows.

---

docs/en/device/npu.md
docs/en/index.rst
docs/zh_cn/device/npu_zh.md
docs/zh_cn/index.rst

Add NPU result.
Add docs/en/device/npu.md, add docs/zh_CN/device/npu.md.
None.
None.
**Before PR**:
**After PR**:

[Docs] Add NPU support page

---

.owners.yml

[Fix] update owners

---

tools/analysis_tools/get_flops.py

[Fix] fix get_flops

---

tools/dataset_converters/bgm/preprocess_bgm_dataset.py
tools/dataset_converters/comp1k/evaluate_comp1k.py
tools/dataset_converters/comp1k/extend_fg.py
tools/dataset_converters/comp1k/filter_comp1k_anno.py
tools/dataset_converters/comp1k/preprocess_comp1k_dataset.py
tools/dataset_converters/df2k_ost/preprocess_df2k_ost_dataset.py
tools/dataset_converters/div2k/preprocess_div2k_dataset.py
tools/dataset_converters/vimeo90k/preprocess_vimeo90k_dataset.py

[Fix] replace mmcv utils by mmengine

---

mmedit/apis/inferencers/controlnet_animation_inferencer.py

[Fix] fix controlnet animation when image shape is not 64x

---

mmedit/engine/optimizers/multi_optimizer_constructor.py
tests/test_engine/test_optimizers/test_multi_optimizer_constructor.py

Some algorithms only optimize parameters of one or a few submodules (e.g. Dreambooth). However, `MultiOptimWrapperConstructor` only support this feature for the first-class submodules.
As title.
Example 1: Build multi optimizers for specific submodules:
```python
class GAN(nn.Module):
def __init__(self) -> None:
super().__init__()
self.generator = nn.Conv2d(3, 3, 1)
self.discriminator = nn.Conv2d(3, 3, 1)
class TextEncoder(nn.Module):
def __init__(self):
super().__init__()
self.embedding = nn.Embedding(100, 100)
class …
```

[Enhancement] Support define modules to be optimized by name and regularization expression

---

mmedit/engine/hooks/visualization_hook.py
mmedit/models/data_preprocessors/edit_data_preprocessor.py
mmedit/visualization/gen_visualizer.py
tests/test_engine/test_hooks/test_visualization_hook.py

* `EditDataPreprocessor` will raise too much warning when `data_keys` is not found.
* `num_samples` and `batch_size` in `GenVisualizationHook` may conflict.
* Some typos exist in the docstring of `GenVisualizer` and `GenVisualizationHook`.
As title.
If this PR introduces a …

[Enhancement] Revise visualization, visualizer and data preprocessor

---

configs/dreambooth/README.md
configs/dreambooth/dreambooth-finetune_text_encoder.py
configs/dreambooth/dreambooth-lora-prior_pre.py
configs/dreambooth/dreambooth-lora.py
configs/dreambooth/dreambooth-prior_pre.py
configs/dreambooth/dreambooth.py
configs/dreambooth/metafile.yml
mmedit/datasets/__init__.py
mmedit/datasets/controlnet_dataset.py
mmedit/datasets/dreambooth_dataset.py
mmedit/models/editors/__init__.py
mmedit/models/editors/dreambooth/__init__.py
mmedit/models/editors/dreambooth/dreambooth.py
mmedit/models/editors/stable_diffusion/stable_diffusion.py
model-index.yml
tests/test_datasets/test_dreambooth_dataset.py
tests/test_models/test_editors/test_dreambooth/test_dreambooth.py

support DreamBooth and SD Finetuning

---

.github/CONTRIBUTING.md
.github/ISSUE_TEMPLATE/1-bug-report.yml
.github/ISSUE_TEMPLATE/2-feature-request.yml
.github/ISSUE_TEMPLATE/4-documentation.yml
.github/ISSUE_TEMPLATE/config.yml
.github/pull_request_template.md
demo/README.md
demo/mmediting_inference_demo.py
demo/mmediting_inference_tutorial.ipynb
docker/Dockerfile
docker/README.md
mmagic/evaluation/functional/inception_utils.py
mmagic/utils/__init__.py
mmagic/utils/io_utils.py

[Rename] update mmagic's demo, .github, docker

---

demo/gradio_controlnet_animation.py
demo/mmediting_inference_demo.py
mmagic/apis/inferencers/base_mmagic_inferencer.py
mmagic/apis/inferencers/colorization_inferencer.py
mmagic/apis/inferencers/conditional_inferencer.py
mmagic/apis/inferencers/controlnet_animation_inferencer.py
mmagic/apis/inferencers/eg3d_inferencer.py
mmagic/apis/inferencers/image_super_resolution_inferencer.py
mmagic/apis/inferencers/inpainting_inferencer.py
mmagic/apis/inferencers/matting_inferencer.py
mmagic/apis/inferencers/text2image_inferencer.py
mmagic/apis/inferencers/translation_inferencer.py
mmagic/apis/inferencers/unconditional_inferencer.py
mmagic/apis/inferencers/video_interpolation_inferencer.py
mmagic/apis/inferencers/video_restoration_inferencer.py
mmagic/mmagic.py
tests/test_apis/test_inferencers/test_base_mmedit_inferencer.py
tests/test_mmagic.py

[Rename] rename to mmagic in inferencers

---

mmagic/datasets/transforms/generate_frame_indices.py

Fix typo: "augmention" to "augmentation".

[Fix]Fix 'augmention' typo

---

demo/README.md
demo/mmagic_inference_tutorial.ipynb
mmagic/apis/mmagic_inferencer.py
tests/test_apis/test_inferencers/test_base_mmedit_inferencer.py
tests/test_apis/test_inferencers/test_mmedit_inferencer.py
tests/test_apis/test_mmagic_inferencer.py

[Rename] erase mmediting traces in some files left behind

---

demo/README.md
demo/mmagic_inference_demo.py

[Fix] replace t2i demo from disco to sd

---

docs/en/conf.py
docs/zh_cn/conf.py

[Enhancement] update mmagic readthedocs

---

mmagic/models/diffusion_schedulers/ddpm_scheduler.py

Remove redundant and no-implementation method `match_shape()` in ddpm scheduler.
Remove redundant and no-implementation method `match_shape()` in ddpm scheduler. (Refer to the implementation in `EditDDIMScheduler`)
If this PR introduces a new feature, it is better to list …

[Fix] remove redundant method in ddpm scheduler (no implementation)

---

.owners.yml

[Fix] del owner

---

requirements/optional.txt
requirements/runtime.txt

[Fix] add controlnet_aux requirements

---

README.md
README_zh-CN.md
configs/controlnet_animation/README.md

[Enhancement] add some guide to controlnet animation

---

configs/dreambooth/README.md
mmagic/models/utils/model_utils.py

[Fix] fix dreambooth

---

configs/inst_colorization/inst-colorizatioon_full_official_cocostuff-256x256.py

[Fix] fix inst-colorization PackInputs

---

requirements/optional.txt
requirements/runtime.txt

[Fix] fix transformers requirements

---

mmagic/apis/inferencers/conditional_inferencer.py
mmagic/apis/inferencers/unconditional_inferencer.py

[Fix] fix GAN inferencer visualization

---

.owners.yml

[Fix] fix owners

---

configs/dreambooth/README.md

fix typo in README.md
fix typo in README.md
**Before PR**:
**After PR**:

[Fix] fix dreambooth typo

---

.github/workflows/pr_stage_test.yml
mmagic/models/utils/tome_utils.py
tests/test_models/test_editors/test_stable_diffusion/test_stable_diffusion_tomesd.py

[Fix] fix sd_tome ut

---

demo/README.md
mmagic/apis/inferencers/matting_inferencer.py
mmagic/apis/mmagic_inferencer.py

[Enhancement] support all matting models inferencer

---

docs/en/get_started/quick_run.md
requirements/docs.txt

[Doc] update quickrun doc

---

.owners.yml
demo/README.md
mmagic/apis/inferencers/image_super_resolution_inferencer.py
mmagic/apis/inferencers/video_interpolation_inferencer.py
mmagic/apis/inferencers/video_restoration_inferencer.py

[Fix] fix isr, vsr, vfi inferencer

---

mmagic/models/archs/wrapper.py
mmagic/models/editors/controlnet/controlnet.py
mmagic/models/editors/dreambooth/dreambooth.py
mmagic/models/editors/stable_diffusion/stable_diffusion.py
tests/test_models/test_editors/test_dreambooth/test_dreambooth.py

Support set `dtype` for each sub-module of Stable Diffusion
`DiffusersWrapper` is revised, and some minor modifications are added to stable diffusion as well.
**Before …

[Enhancement] Support `dtype` for submodule of StableDiffusion

---

mmagic/models/archs/tokenizer.py
mmagic/models/editors/disco_diffusion/clip_wrapper.py
tests/test_models/test_archs/test_tokenizer.py
tests/test_models/test_editors/test_disco_diffusion/test_disco_diffusion_clip_wrapper.py

Textual inversion requires add external embedding to CLIP's embedding layer.
As title.
**Before PR**:
**After PR**:

[Enhancement] Support external embedding for clip wrapper

---

configs/controlnet/controlnet-1xb1-fill50k.py

The name of the configuration file is inconsistent with the name of the registrar, causing the loading failure.
Modifying the configuration file
**Before PR**:
**After …

[Fix] fix the dataset name

---

mmagic/apis/inferencers/controlnet_animation_inferencer.py

[Enhance] add output fps control for controlnet animation

---

README.md
README_zh-CN.md
docs/en/changelog.md
docs/zh_cn/changelog.md
mmagic/version.py

[Release] v1.0.1

---

mmagic/version.py

[Release] post release for v1.0.1

---

mmagic/models/editors/stable_diffusion/stable_diffusion.py

StableDiffusion's `infer` use `self.scheduler` instead of `self.test_scheduler`.
As title.
**Before PR**:
**After PR**:

[Fix] Fix set timestep in stable diffusion's infer

---

docs/zh_cn/howto/models.md
docs/zh_cn/howto/transforms.md

Community tasks ID 15, Translation and improvement of  1.x Chinese Documentation. 
Translate the models.md and transforms.md files in the howto folder into Chinese. …

[Doc] add zh_cn docs of models and transforms

---

mmagic/apis/__init__.py
projects/glide/configs/README.md

[Fix] fix init_model and glide demo

---

docs/zh_cn/get_started/install.md

Community tasks ID 163, Translation and improvement of docs/en/get_started/install.md.
Translating the install.md in the docs/en/get_started folder and add to docs/zh_cn/get_started folder.
the modification doesn't introduce changes that break the backward-compatibility of the downstream repositories.
**Before PR**:
**After PR**:

[Doc] add zh-cn intall doc in get_started

---

mmagic/models/editors/inst_colorization/color_utils.py

[Fix] fix InstColorization bug when dim=3

---

configs/deepfillv1/README.md
configs/deepfillv1/README_zh-CN.md
configs/deepfillv1/metafile.yml
configs/deepfillv2/README.md
configs/deepfillv2/README_zh-CN.md
configs/deepfillv2/metafile.yml
demo/README.md
mmagic/apis/inferencers/eg3d_inferencer.py

[Doc] improve demo document

---

configs/_base_/datasets/deblurring-motion_test_config.py
configs/_base_/datasets/denoising-real_test_config.py
configs/restormer/README.md
configs/restormer/metafile.yml
configs/swinir/swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-grayCAR10.py
tools/dataset_converters/classic5/README.md
tools/dataset_converters/deraining/README.md
tools/dataset_converters/deraining/README_zh-CN.md
tools/dataset_converters/dpdd/README.md
tools/dataset_converters/dpdd/README_zh-CN.md
tools/dataset_converters/gopro/README.md
tools/dataset_converters/gopro/README_zh-CN.md
tools/dataset_converters/sidd/README.md
tools/dataset_converters/sidd/README_zh-CN.md
tools/dataset_converters/sidd/preprocess_sidd_test_dataset.py

[Fix] fix some dataset converters typos

---

docs/zh_cn/community/projects.md

DID: D_kwDOI32y584AURZm from https://aicarrier.feishu.cn/sheets/shtcnE5FlKLcg4vMjMMoq4kFL1f?sheet=db3ad0
Translate `docs/en/community/projects.md` to `docs/zh_cn/community/projects.md`
Translate `docs/en/community/projects.md` to `docs/zh_cn/community/projects.md`
If this PR …

[Doc] add zh_cn projects docs

---

.dev_scripts/inference_benchmark.sh
.dev_scripts/test_benchmark.yml
.dev_scripts/train_benchmark.yml
configs/_base_/datasets/deblurring-motion_test_config.py
configs/_base_/datasets/denoising-real_test_config.py
configs/restormer/README.md
configs/restormer/metafile.yml
configs/swinir/swinir_s126w7d6e180_8xb1-lr2e-4-1600k_dfwb-grayCAR10.py
docs/zh_cn/get_started/quick_run.md
mmagic/apis/inferencers/controlnet_animation_inferencer.py
mmagic/models/editors/controlnet/controlnet.py
mmagic/models/editors/dreambooth/dreambooth.py
mmagic/models/editors/stable_diffusion/stable_diffusion.py
tools/dataset_converters/classic5/README.md
tools/dataset_converters/deraining/README.md
tools/dataset_converters/deraining/README_zh-CN.md
tools/dataset_converters/dpdd/README.md
tools/dataset_converters/dpdd/README_zh-CN.md
tools/dataset_converters/gopro/README.md
tools/dataset_converters/gopro/README_zh-CN.md
tools/dataset_converters/sidd/README.md
tools/dataset_converters/sidd/README_zh-CN.md
tools/dataset_converters/sidd/preprocess_sidd_test_dataset.py

Merge test branch

---

docs/en/user_guides/inference.md

#1919 
This is a task received from the contributor communication group. I'm glad to contribute to the openmmlab open source community.
Update the markdown file https://github.com/open-mmlab/mmagic/blob/main/docs/en/user_guides/inference.md
**Before PR**:
**After PR**:

[Docs] update inference demo markdown

---

docs/en/howto/dataset.md
docs/zh_cn/howto/dataset.md

Translate "How to prepare your own datasets“
Translate "How to prepare your own datasets“
N/A
N/A

Translate "How to prepare your own datasets“

---

docs/zh_cn/migration/models.md

translation work has been done, please check it.

Translate models.md's en version into chinese

---

docker/Dockerfile
requirements/tests.txt

fix some bug in requirements and DockerFile
When build with DockerFile, Error may occur in line13 "apt-get" because of no key, Error may occur in line19 "git clone" because of no permission, Error may occur in line24 "pip install" because of "Double requirement given for 'transform'".
**Before PR**:
**After PR**:

requirements and DockerFile bugs

---

docs/en/advanced_guides/evaluator.md
docs/zh_cn/advanced_guides/evaluator.md

add evaluator document_en and fix some errors in evaluator doc_zh_CN

[CodeCamp2023-551] advanced_guides/evaluator.md

---

docs/en/advanced_guides/data_flow.md
docs/zh_cn/advanced_guides/data_flow.md

[CodeCamp2023-549] Dataflow doc

---

mmagic/datasets/transforms/albu_function.py

as title.
**Before PR**:
**After PR**:

[Docs ]improve docstring coverage

---

docs/zh_cn/user_guides/inference.md

[codecamp 2023-597] 0822 commit,updata inference

---

tests/test_apis/test_mmagic_inferencer.py
tests/test_models/test_diffusion_schedulers/test_ddim_scheduler.py
tests/test_models/test_losses/test_clip_loss.py

[FIX] remove code and fix clip loss ut test

---

tests/test_models/test_editors/test_controlnet/test_controlnet.py
tests/test_models/test_editors/test_dreambooth/test_dreambooth.py
tests/test_models/test_editors/test_fastcomposer/test_fastcomposer.py
tests/test_models/test_editors/test_vico/test_vico.py

Faster test by using tiny-sd.
**Before PR**:
**After PR**:

[Enhance] faster test

---

README.md
README_zh-CN.md

Add OpenXLab Badge to share official applications, community applications and ecological applications based on MMAgic in the OpenXLab platform.
Added OpenXLab Badge in ReadME（English & Chinese）.
If this PR introduces a new feature, it is better to list some use cases here, …

Add OpenXLab Badge

---

docs/zh_cn/changelog.md
mmagic/version.py

[Release] Post release for v1.1.0

---

.readthedocs.yml

[Fix] fix readthedocs building

---

configs/animatediff/README.md
configs/animatediff/metafile.yml

add openxlab download in README
add openxlab download in README
**Before PR**:
**After PR**:

[Fix] animatediff download from openxlab

---

mmagic/models/archs/lora.py

update support for latest diffusers with lora

---

.github/workflows/pr_stage_test.yml
mmagic/models/editors/arcface/id_loss.py
requirements/runtime.txt
tests/test_models/test_archs/test_wrapper.py
tests/test_models/test_base_models/test_base_edit_model.py

[Fix] Update diffusers to v0.23.0

---

README.md
README_zh-CN.md
docs/en/changelog.md
docs/zh_cn/changelog.md
mmagic/version.py
projects/powerpaint/README.md
projects/powerpaint/gradio_PowerPaint.py

[Release] Release v1.2.0

---

mmagic/version.py

[Release] Post release for v1.2.0

---

projects/powerpaint/README.md
projects/powerpaint/gradio_PowerPaint.py

[Fix] fix bug of controlnet in powerpaint

---

projects/magicmaker/index.html

index_html for magicmaker on openxlab

---

README.md
README_zh-CN.md

update link of openxlab badge
